In [1]:
import os
import re
import pandas as pd
import numpy as np

# 1、原始数据:reads_1.fq 和 reads_2.fq

In [ ]:
name_dict = {
    1: '3dpi_N289D_C57mouse_Lung',
    2: '3dpi_T7_C57mouse_Lung',
    3: '3dpi_HY_C57mouse_Lung',
    4: '3dpi_0_C57mouse_Lung',
    5: '3dpi_KT_C57mouse_Lung',
    6: '5dpi_N289D_C57mouse_Lung',
    7: '5dpi_T7_C57mouse_Lung',
    8: '5dpi_0_C57mouse_Lung',
    9: '5dpi_HY_C57mouse_Lung',
    10: '5dpi_KT_C57mouse_Lung',
}

src_path = '/data/shenlab_data/01.Data_Sequencing/030.HA转录组20240123/DATA_20240121023900_1/data'

for i in range(1, 11):
    new_name = name_dict[i]
    i = f'0{i}' if i < 10 else f'{i}'
    for j in range(1, 3):
        print(j)
        path_0 = f'{src_path}/Unknown_BU999-001T00{i}_good_{j}.fq.gz'
        path_1 = f'data/{new_name}_{j}.fq.gz'
        cmd = f'ln -s {path_0} {path_1}'
        
        if os.path.exists(path_0):
            os.system(cmd)

# 2、使用Hisat2将reads映射到参考基因组

输入文件:reads_1.fq, reads_2.fq, 参考基因组基因组索引文件

输出文件:alignments.sam

hisat2 -p 8 -x genome_index -1 reads_1.fq -2 reads_2.fq -S alignments.samhisat2 -p 8 -x genome_index -1 reads_1.fq -2 reads_2.fq -S alignments.sam

In [369]:
grcm38_index = 'assets/grcm38_tran/genome_tran'

cmd_list = []

for file in os.listdir('data'):
    
    if not file.endswith('_1.fq.gz'):
        continue
        
    sample = file.replace('_1.fq.gz', '')
    
    hisat2_cmd = f'hisat2 --dta -p 4 -x {grcm38_index} -1 data/{sample}_1.fq.gz -2 data/{sample}_2.fq.gz -S outputs/hisat2_outputs/{sample}.hisat2.sam'
    
    cmd_list.append(hisat2_cmd)
    
print(' & '.join(cmd_list))

hisat2 --dta -p 4 -x assets/grcm38_tran/genome_tran -1 data/5dpi_KT_C57mouse_Lung_1.fq.gz -2 data/5dpi_KT_C57mouse_Lung_2.fq.gz -S outputs/hisat2_outputs/5dpi_KT_C57mouse_Lung.hisat2.sam & hisat2 --dta -p 4 -x assets/grcm38_tran/genome_tran -1 data/3dpi_N289D_C57mouse_Lung_1.fq.gz -2 data/3dpi_N289D_C57mouse_Lung_2.fq.gz -S outputs/hisat2_outputs/3dpi_N289D_C57mouse_Lung.hisat2.sam & hisat2 --dta -p 4 -x assets/grcm38_tran/genome_tran -1 data/3dpi_0_C57mouse_Lung_1.fq.gz -2 data/3dpi_0_C57mouse_Lung_2.fq.gz -S outputs/hisat2_outputs/3dpi_0_C57mouse_Lung.hisat2.sam & hisat2 --dta -p 4 -x assets/grcm38_tran/genome_tran -1 data/5dpi_N289D_C57mouse_Lung_1.fq.gz -2 data/5dpi_N289D_C57mouse_Lung_2.fq.gz -S outputs/hisat2_outputs/5dpi_N289D_C57mouse_Lung.hisat2.sam & hisat2 --dta -p 4 -x assets/grcm38_tran/genome_tran -1 data/5dpi_HY_C57mouse_Lung_1.fq.gz -2 data/5dpi_HY_C57mouse_Lung_2.fq.gz -S outputs/hisat2_outputs/5dpi_HY_C57mouse_Lung.hisat2.sam & hisat2 --dta -p 4 -x assets/grcm38_tran/genome_tran -1 data/5dpi_0_C57mouse_Lung_1.fq.gz -2 data/5dpi_0_C57mouse_Lung_2.fq.gz -S outputs/hisat2_outputs/5dpi_0_C57mouse_Lung.hisat2.sam & hisat2 --dta -p 4 -x assets/grcm38_tran/genome_tran -1 data/3dpi_T7_C57mouse_Lung_1.fq.gz -2 data/3dpi_T7_C57mouse_Lung_2.fq.gz -S outputs/hisat2_outputs/3dpi_T7_C57mouse_Lung.hisat2.sam & hisat2 --dta -p 4 -x assets/grcm38_tran/genome_tran -1 data/5dpi_T7_C57mouse_Lung_1.fq.gz -2 data/5dpi_T7_C57mouse_Lung_2.fq.gz -S outputs/hisat2_outputs/5dpi_T7_C57mouse_Lung.hisat2.sam & hisat2 --dta -p 4 -x assets/grcm38_tran/genome_tran -1 data/3dpi_KT_C57mouse_Lung_1.fq.gz -2 data/3dpi_KT_C57mouse_Lung_2.fq.gz -S outputs/hisat2_outputs/3dpi_KT_C57mouse_Lung.hisat2.sam & hisat2 --dta -p 4 -x assets/grcm38_tran/genome_tran -1 data/3dpi_HY_C57mouse_Lung_1.fq.gz -2 data/3dpi_HY_C57mouse_Lung_2.fq.gz -S outputs/hisat2_outputs/3dpi_HY_C57mouse_Lung.hisat2.sam

# 3、将sam文件转换为bam文件

输入文件:alignments.sam

输出文件:alignments.bam

samtools view -Sb alignments.sam > alignments.bamsamtools view -Sb alignments.sam > alignments.bam

In [377]:
for sam_file in os.listdir('outputs/hisat2_outputs'):
    
    if not sam_file.endswith('.hisat2.sam'):
        continue
        
    cmd_0 = f'samtools view -bS outputs/hisat2_outputs/{sam_file} > outputs/hisat2_outputs/{sam_file.replace(".sam", "")}.bam'
        
    print(cmd_0)
    
    os.system(cmd_0)

samtools view -bS outputs/hisat2_outputs/3dpi_KT_C57mouse_Lung.hisat2.sam > outputs/hisat2_outputs/3dpi_KT_C57mouse_Lung.hisat2.bam
samtools view -bS outputs/hisat2_outputs/3dpi_HY_C57mouse_Lung.hisat2.sam > outputs/hisat2_outputs/3dpi_HY_C57mouse_Lung.hisat2.bam
samtools view -bS outputs/hisat2_outputs/3dpi_T7_C57mouse_Lung.hisat2.sam > outputs/hisat2_outputs/3dpi_T7_C57mouse_Lung.hisat2.bam
samtools view -bS outputs/hisat2_outputs/5dpi_HY_C57mouse_Lung.hisat2.sam > outputs/hisat2_outputs/5dpi_HY_C57mouse_Lung.hisat2.bam
samtools view -bS outputs/hisat2_outputs/3dpi_0_C57mouse_Lung.hisat2.sam > outputs/hisat2_outputs/3dpi_0_C57mouse_Lung.hisat2.bam
samtools view -bS outputs/hisat2_outputs/3dpi_N289D_C57mouse_Lung.hisat2.sam > outputs/hisat2_outputs/3dpi_N289D_C57mouse_Lung.hisat2.bam
samtools view -bS outputs/hisat2_outputs/5dpi_0_C57mouse_Lung.hisat2.sam > outputs/hisat2_outputs/5dpi_0_C57mouse_Lung.hisat2.bam
samtools view -bS outputs/hisat2_outputs/5dpi_N289D_C57mouse_Lung.hisat2.sam > outputs/hisat2_outputs/5dpi_N289D_C57mouse_Lung.hisat2.bam
samtools view -bS outputs/hisat2_outputs/5dpi_KT_C57mouse_Lung.hisat2.sam > outputs/hisat2_outputs/5dpi_KT_C57mouse_Lung.hisat2.bam
samtools view -bS outputs/hisat2_outputs/5dpi_T7_C57mouse_Lung.hisat2.sam > outputs/hisat2_outputs/5dpi_T7_C57mouse_Lung.hisat2.bam

In [ ]:
cmds = []

for sam_file in os.listdir('outputs/hisat2_outputs'):
    
    if not sam_file.endswith('.hisat2.sam'):
        continue
        
    sample = sam_file.replace('.hisat2.sam', '')
    
    cmd_0 = f'samtools view -bS outputs/hisat2_outputs/{sam_file} > outputs/hisat2_outputs/{sample}.bam' # 将SAM文件转换为BAM文件
    cmd_1 = f'samtools sort outputs/hisat2_outputs/{sample}.bam -o outputs/hisat2_outputs/{sample}.sorted.bam' # 对BAM文件进行排序
    cmd_2 = f'samtools index outputs/hisat2_outputs/{sample}.sorted.bam' # 为BAM文件创建索引
    
    cmd = f'{cmd_0} && {cmd_1} && {cmd_2}'
    
    print(f'{cmd}\n')
    
    os.system(cmd)

samtools view -bS outputs/hisat2_outputs/3dpi_KT_C57mouse_Lung.hisat2.sam > outputs/hisat2_outputs/3dpi_KT_C57mouse_Lung.bam

Error, dont recognize --est_method featureCounts  at /home/chenrujian/trinityrnaseq-v2.15.1/util/abundance_estimates_to_matrix.pl line 81.
Error, dont recognize --est_method featureCounts  at /home/chenrujian/trinityrnaseq-v2.15.1/util/abundance_estimates_to_matrix.pl line 81.

samtools view -bS outputs/hisat2_outputs/3dpi_HY_C57mouse_Lung.hisat2.sam > outputs/hisat2_outputs/3dpi_HY_C57mouse_Lung.bam

samtools view -bS outputs/hisat2_outputs/3dpi_T7_C57mouse_Lung.hisat2.sam > outputs/hisat2_outputs/3dpi_T7_C57mouse_Lung.bam

Error, dont recognize --est_method featureCounts  at /home/chenrujian/trinityrnaseq-v2.15.1/util/abundance_estimates_to_matrix.pl line 81.
Error, dont recognize --est_method featureCounts  at /home/chenrujian/trinityrnaseq-v2.15.1/util/abundance_estimates_to_matrix.pl line 81.

samtools view -bS outputs/hisat2_outputs/5dpi_HY_C57mouse_Lung.hisat2.sam > outputs/hisat2_outputs/5dpi_HY_C57mouse_Lung.bam

samtools view -bS outputs/hisat2_outputs/3dpi_0_C57mouse_Lung.hisat2.sam > outputs/hisat2_outputs/3dpi_0_C57mouse_Lung.bam

Error, dont recognize --est_method featureCounts  at /home/chenrujian/trinityrnaseq-v2.15.1/util/abundance_estimates_to_matrix.pl line 81.
Error, dont recognize --est_method featureCounts  at /home/chenrujian/trinityrnaseq-v2.15.1/util/abundance_estimates_to_matrix.pl line 81.

samtools view -bS outputs/hisat2_outputs/3dpi_N289D_C57mouse_Lung.hisat2.sam > outputs/hisat2_outputs/3dpi_N289D_C57mouse_Lung.bam

samtools view -bS outputs/hisat2_outputs/5dpi_0_C57mouse_Lung.hisat2.sam > outputs/hisat2_outputs/5dpi_0_C57mouse_Lung.bam

Error, dont recognize --est_method featureCounts  at /home/chenrujian/trinityrnaseq-v2.15.1/util/abundance_estimates_to_matrix.pl line 81.
Error, dont recognize --est_method featureCounts  at /home/chenrujian/trinityrnaseq-v2.15.1/util/abundance_estimates_to_matrix.pl line 81.

samtools view -bS outputs/hisat2_outputs/5dpi_N289D_C57mouse_Lung.hisat2.sam > outputs/hisat2_outputs/5dpi_N289D_C57mouse_Lung.bam

samtools view -bS outputs/hisat2_outputs/5dpi_KT_C57mouse_Lung.hisat2.sam > outputs/hisat2_outputs/5dpi_KT_C57mouse_Lung.bam

samtools view -bS outputs/hisat2_outputs/5dpi_T7_C57mouse_Lung.hisat2.sam > outputs/hisat2_outputs/5dpi_T7_C57mouse_Lung.bam

Error, dont recognize --est_method featureCounts  at /home/chenrujian/trinityrnaseq-v2.15.1/util/abundance_estimates_to_matrix.pl line 81.
Error, dont recognize --est_method featureCounts  at /home/chenrujian/trinityrnaseq-v2.15.1/util/abundance_estimates_to_matrix.pl line 81.

# 4、使用featureCounts计算基因表达量

输入文件:alignments.bam, 基因注释文件gene.gtf

输出文件:counts.txt

featureCounts -a gene.gtf -o counts.txt alignments.bamfeatureCounts -a gene.gtf -o counts.txt alignments.bam

In [ ]:
annotation_gtf = 'assets/grcm38_tran/Mus_musculus.GRCm38.84.gtf'

counts_txt = f'outputs/featureCounts_outputs/featurecounts.txt'

featureCounts_cmd = f'featureCounts -a {annotation_gtf} -o {counts_txt} -p -t exon -g gene_id'

for sam_file in os.listdir('outputs/hisat2_outputs'):
    
    if not sam_file.endswith('.sorted.bam'):
        continue
        
    sample = sam_file.replace('.sorted.bam', '')
    sample_bam = f'outputs/hisat2_outputs/{sample}.sorted.bam'
    
    featureCounts_cmd += f' {sample_bam}'
    
print(featureCounts_cmd)
    
os.system(featureCounts_cmd)

featureCounts -a assets/grcm38_tran/Mus_musculus.GRCm38.84.gtf -o outputs/featureCounts_outputs/featurecounts.txt -p -t exon -g gene_id outputs/hisat2_outputs/5dpi_N289D_C57mouse_Lung.sorted.bam outputs/hisat2_outputs/3dpi_KT_C57mouse_Lung.sorted.bam outputs/hisat2_outputs/5dpi_HY_C57mouse_Lung.sorted.bam outputs/hisat2_outputs/3dpi_HY_C57mouse_Lung.sorted.bam outputs/hisat2_outputs/5dpi_T7_C57mouse_Lung.sorted.bam outputs/hisat2_outputs/5dpi_0_C57mouse_Lung.sorted.bam outputs/hisat2_outputs/3dpi_T7_C57mouse_Lung.sorted.bam outputs/hisat2_outputs/3dpi_0_C57mouse_Lung.sorted.bam outputs/hisat2_outputs/3dpi_N289D_C57mouse_Lung.sorted.bam outputs/hisat2_outputs/5dpi_KT_C57mouse_Lung.sorted.bam

        ==========     _____ _    _ ____  _____  ______          _____
        =====         / ____| |  | |  _ \|  __ \|  ____|   /\   |  __ \
          =====      | (___ | |  | | |_) | |__) | |__     /  \  | |  | |
            ====      \___ \| |  | |  _ <|  _  /|  __|   / /\ \ | |  | |
              ====    ____) | |__| | |_) | | \ \| |____ / ____ \| |__| |
        ==========   |_____/ \____/|____/|_|  \_\______/_/    \_\_____/
	  v2.0.6

//========================== featureCounts setting ===========================\\
||                                                                            ||
||             Input files : 10 BAM files                                     ||
||                                                                            ||
||                           5dpi_N289D_C57mouse_Lung.sorted.bam              ||
||                           3dpi_KT_C57mouse_Lung.sorted.bam                 ||
||                           5dpi_HY_C57mouse_Lung.sorted.bam                 ||
||                           3dpi_HY_C57mouse_Lung.sorted.bam                 ||
||                           5dpi_T7_C57mouse_Lung.sorted.bam                 ||
||                           5dpi_0_C57mouse_Lung.sorted.bam                  ||
||                           3dpi_T7_C57mouse_Lung.sorted.bam                 ||
||                           3dpi_0_C57mouse_Lung.sorted.bam                  ||
||                           3dpi_N289D_C57mouse_Lung.sorted.bam              ||
||                           5dpi_KT_C57mouse_Lung.sorted.bam                 ||
||                                                                            ||
||             Output file : featurecounts.txt                                ||
||                 Summary : featurecounts.txt.summary                        ||
||              Paired-end : yes                                              ||
||        Count read pairs : no                                               ||
||              Annotation : Mus_musculus.GRCm38.84.gtf (GTF)                 ||
||      Dir for temp files : outputs/featureCounts_outputs                    ||
||                                                                            ||
||                 Threads : 1                                                ||
||                   Level : meta-feature level                               ||
||      Multimapping reads : not counted                                      ||
|| Multi-overlapping reads : not counted                                      ||
||   Min overlapping bases : 1                                                ||
||                                                                            ||
\\============================================================================//

//================================= Running ==================================\\
||                                                                            ||
|| Load annotation file Mus_musculus.GRCm38.84.gtf ...                        ||
||    Features : 710016                                                       ||
||    Meta-features : 47729                                                   ||
||    Chromosomes/contigs : 45                                                ||
||                                                                            ||
|| Process BAM file 5dpi_N289D_C57mouse_Lung.sorted.bam...                    ||
||    Paired-end reads are included.                                          ||
||    The reads are assigned on the single-end mode.                          ||
||    Total alignments : 53052116                                             ||
||    Successfully assigned alignments : 42280009 (79.7%)                     ||
||    Running time : 6.97 minutes                                             ||
||                                                                            ||
|| Process BAM file 3dpi_KT_C57mouse_Lung.sorted.bam...                       ||
||    Paired-end reads are included.                                          ||
||    The reads are assigned on the single-end mode.                          ||
||    Total alignments : 64475396                                             ||
||    Successfully assigned alignments : 51178912 (79.4%)                     ||
||    Running time : 6.35 minutes                                             ||
||                                                                            ||
|| Process BAM file 5dpi_HY_C57mouse_Lung.sorted.bam...                       ||
||    Paired-end reads are included.                                          ||
||    The reads are assigned on the single-end mode.                          ||
||    Total alignments : 60314777                                             ||
||    Successfully assigned alignments : 48274710 (80.0%)                     ||
||    Running time : 5.34 minutes                                             ||
||                                                                            ||
|| Process BAM file 3dpi_HY_C57mouse_Lung.sorted.bam...                       ||
||    Paired-end reads are included.                                          ||
||    The reads are assigned on the single-end mode.                          ||
||    Total alignments : 44393304                                             ||
||    Successfully assigned alignments : 35475677 (79.9%)                     ||
||    Running time : 4.65 minutes                                             ||
||                                                                            ||
|| Process BAM file 5dpi_T7_C57mouse_Lung.sorted.bam...                       ||
||    Paired-end reads are included.                                          ||
||    The reads are assigned on the single-end mode.                          ||
||    Total alignments : 52247544                                             ||
||    Successfully assigned alignments : 39733026 (76.0%)                     ||
||    Running time : 5.35 minutes                                             ||
||                                                                            ||
|| Process BAM file 5dpi_0_C57mouse_Lung.sorted.bam...                        ||
||    Paired-end reads are included.                                          ||
||    The reads are assigned on the single-end mode.                          ||
||    Total alignments : 44488675                                             ||
||    Successfully assigned alignments : 35001770 (78.7%)                     ||
||    Running time : 3.95 minutes                                             ||
||                                                                            ||
|| Process BAM file 3dpi_T7_C57mouse_Lung.sorted.bam...                       ||
||    Paired-end reads are included.                                          ||
||    The reads are assigned on the single-end mode.                          ||
||    Total alignments : 45242173                                             ||
||    Successfully assigned alignments : 35448318 (78.4%)                     ||
||    Running time : 4.93 minutes                                             ||
||                                                                            ||
|| Process BAM file 3dpi_0_C57mouse_Lung.sorted.bam...                        ||
||    Paired-end reads are included.                                          ||
||    The reads are assigned on the single-end mode.                          ||
||    Total alignments : 66806874                                             ||
||    Successfully assigned alignments : 45494635 (68.1%)                     ||
||    Running time : 5.41 minutes                                             ||
||                                                                            ||
|| Process BAM file 3dpi_N289D_C57mouse_Lung.sorted.bam...                    ||
||    Paired-end reads are included.                                          ||
||    The reads are assigned on the single-end mode.                          ||
||    Total alignments : 57362577                                             ||
||    Successfully assigned alignments : 44924013 (78.3%)                     ||
||    Running time : 5.26 minutes                                             ||
||                                                                            ||
|| Process BAM file 5dpi_KT_C57mouse_Lung.sorted.bam...                       ||
||    Paired-end reads are included.                                          ||
||    The reads are assigned on the single-end mode.                          ||
||    Total alignments : 59176993                                             ||
||    Successfully assigned alignments : 46149004 (78.0%)                     ||
||    Running time : 7.15 minutes                                             ||
||                                                                            ||
|| Write the final count table.                                               ||
|| Write the read assignment summary.                                         ||
||                                                                            ||
|| Summary of counting results can be found in file "outputs/featureCounts_o  ||
|| utputs/featurecounts.txt.summary"                                          ||
||                                                                            ||
\\============================================================================//

0

In [ ]:
annotation_gtf = 'assets/grcm38_tran/Mus_musculus.GRCm38.84.gtf'

for sam_file in os.listdir('outputs/hisat2_outputs'):
    
    if not sam_file.endswith('.sorted.bam'):
        continue
        
    sample = sam_file.replace('.sorted.bam', '')
    sample_bam = f'outputs/hisat2_outputs/{sample}.sorted.bam'
    counts_txt = f'outputs/featureCounts_outputs/{sample}.featurecounts.txt'
    
    featureCounts_cmd = f'featureCounts -a {annotation_gtf} -o {counts_txt} -p -t exon -g gene_id {sample_bam}'
    
    print(featureCounts_cmd, '\n')
    
    os.system(featureCounts_cmd)

featureCounts -a assets/grcm38_tran/Mus_musculus.GRCm38.84.gtf -o outputs/featureCounts_outputs/5dpi_N289D_C57mouse_Lung.featurecounts.txt -p -t exon -g gene_id outputs/hisat2_outputs/5dpi_N289D_C57mouse_Lung.sorted.bam

        ==========     _____ _    _ ____  _____  ______          _____
        =====         / ____| |  | |  _ \|  __ \|  ____|   /\   |  __ \
          =====      | (___ | |  | | |_) | |__) | |__     /  \  | |  | |
            ====      \___ \| |  | |  _ <|  _  /|  __|   / /\ \ | |  | |
              ====    ____) | |__| | |_) | | \ \| |____ / ____ \| |__| |
        ==========   |_____/ \____/|____/|_|  \_\______/_/    \_\_____/
	  v2.0.6

//========================== featureCounts setting ===========================\\
||                                                                            ||
||             Input files : 1 BAM file                                       ||
||                                                                            ||
||                           5dpi_N289D_C57mouse_Lung.sorted.bam              ||
||                                                                            ||
||             Output file : 5dpi_N289D_C57mouse_Lung.featurecounts.txt       ||
||                 Summary : 5dpi_N289D_C57mouse_Lung.featurecounts.txt.s ... ||
||              Paired-end : yes                                              ||
||        Count read pairs : no                                               ||
||              Annotation : Mus_musculus.GRCm38.84.gtf (GTF)                 ||
||      Dir for temp files : outputs/featureCounts_outputs                    ||
||                                                                            ||
||                 Threads : 1                                                ||
||                   Level : meta-feature level                               ||
||      Multimapping reads : not counted                                      ||
|| Multi-overlapping reads : not counted                                      ||
||   Min overlapping bases : 1                                                ||
||                                                                            ||
\\============================================================================//

//================================= Running ==================================\\
||                                                                            ||
|| Load annotation file Mus_musculus.GRCm38.84.gtf ...                        ||
||    Features : 710016                                                       ||
||    Meta-features : 47729                                                   ||
||    Chromosomes/contigs : 45                                                ||
||                                                                            ||
|| Process BAM file 5dpi_N289D_C57mouse_Lung.sorted.bam...                    ||
||    Paired-end reads are included.                                          ||
||    The reads are assigned on the single-end mode.                          ||
||    Total alignments : 53052116                                             ||
||    Successfully assigned alignments : 42280009 (79.7%)                     ||
||    Running time : 7.33 minutes                                             ||
||                                                                            ||
|| Write the final count table.                                               ||
|| Write the read assignment summary.                                         ||
||                                                                            ||
|| Summary of counting results can be found in file "outputs/featureCounts_o  ||
|| utputs/5dpi_N289D_C57mouse_Lung.featurecounts.txt.summary"                 ||
||                                                                            ||
\\============================================================================//


        ==========     _____ _    _ ____  _____  ______          _____
        =====         / ____| |  | |  _ \|  __ \|  ____|   /\   |  __ \
          =====      | (___ | |  | | |_) | |__) | |__     /  \  | |  | |
            ====      \___ \| |  | |  _ <|  _  /|  __|   / /\ \ | |  | |
              ====    ____) | |__| | |_) | | \ \| |____ / ____ \| |__| |
        ==========   |_____/ \____/|____/|_|  \_\______/_/    \_\_____/
	  v2.0.6

//========================== featureCounts setting ===========================\\
||                                                                            ||
||             Input files : 1 BAM file                                       ||
||                                                                            ||
||                           3dpi_KT_C57mouse_Lung.sorted.bam                 ||
||                                                                            ||
||             Output file : 3dpi_KT_C57mouse_Lung.featurecounts.txt          ||
||                 Summary : 3dpi_KT_C57mouse_Lung.featurecounts.txt.summary  ||
||              Paired-end : yes                                              ||
||        Count read pairs : no                                               ||
||              Annotation : Mus_musculus.GRCm38.84.gtf (GTF)                 ||
||      Dir for temp files : outputs/featureCounts_outputs                    ||
||                                                                            ||
||                 Threads : 1                                                ||
||                   Level : meta-feature level                               ||
||      Multimapping reads : not counted                                      ||
|| Multi-overlapping reads : not counted                                      ||
||   Min overlapping bases : 1                                                ||
||                                                                            ||
\\============================================================================//

//================================= Running ==================================\\
||                                                                            ||
|| Load annotation file Mus_musculus.GRCm38.84.gtf ...                        ||

featureCounts -a assets/grcm38_tran/Mus_musculus.GRCm38.84.gtf -o outputs/featureCounts_outputs/3dpi_KT_C57mouse_Lung.featurecounts.txt -p -t exon -g gene_id outputs/hisat2_outputs/3dpi_KT_C57mouse_Lung.sorted.bam

||    Features : 710016                                                       ||
||    Meta-features : 47729                                                   ||
||    Chromosomes/contigs : 45                                                ||
||                                                                            ||
|| Process BAM file 3dpi_KT_C57mouse_Lung.sorted.bam...                       ||
||    Paired-end reads are included.                                          ||
||    The reads are assigned on the single-end mode.                          ||
||    Total alignments : 64475396                                             ||
||    Successfully assigned alignments : 51178912 (79.4%)                     ||
||    Running time : 9.74 minutes                                             ||
||                                                                            ||
|| Write the final count table.                                               ||
|| Write the read assignment summary.                                         ||
||                                                                            ||
|| Summary of counting results can be found in file "outputs/featureCounts_o  ||
|| utputs/3dpi_KT_C57mouse_Lung.featurecounts.txt.summary"                    ||
||                                                                            ||
\\============================================================================//

featureCounts -a assets/grcm38_tran/Mus_musculus.GRCm38.84.gtf -o outputs/featureCounts_outputs/5dpi_HY_C57mouse_Lung.featurecounts.txt -p -t exon -g gene_id outputs/hisat2_outputs/5dpi_HY_C57mouse_Lung.sorted.bam

        ==========     _____ _    _ ____  _____  ______          _____
        =====         / ____| |  | |  _ \|  __ \|  ____|   /\   |  __ \
          =====      | (___ | |  | | |_) | |__) | |__     /  \  | |  | |
            ====      \___ \| |  | |  _ <|  _  /|  __|   / /\ \ | |  | |
              ====    ____) | |__| | |_) | | \ \| |____ / ____ \| |__| |
        ==========   |_____/ \____/|____/|_|  \_\______/_/    \_\_____/
	  v2.0.6

//========================== featureCounts setting ===========================\\
||                                                                            ||
||             Input files : 1 BAM file                                       ||
||                                                                            ||
||                           5dpi_HY_C57mouse_Lung.sorted.bam                 ||
||                                                                            ||
||             Output file : 5dpi_HY_C57mouse_Lung.featurecounts.txt          ||
||                 Summary : 5dpi_HY_C57mouse_Lung.featurecounts.txt.summary  ||
||              Paired-end : yes                                              ||
||        Count read pairs : no                                               ||
||              Annotation : Mus_musculus.GRCm38.84.gtf (GTF)                 ||
||      Dir for temp files : outputs/featureCounts_outputs                    ||
||                                                                            ||
||                 Threads : 1                                                ||
||                   Level : meta-feature level                               ||
||      Multimapping reads : not counted                                      ||
|| Multi-overlapping reads : not counted                                      ||
||   Min overlapping bases : 1                                                ||
||                                                                            ||
\\============================================================================//

//================================= Running ==================================\\
||                                                                            ||
|| Load annotation file Mus_musculus.GRCm38.84.gtf ...                        ||
||    Features : 710016                                                       ||
||    Meta-features : 47729                                                   ||
||    Chromosomes/contigs : 45                                                ||
||                                                                            ||
|| Process BAM file 5dpi_HY_C57mouse_Lung.sorted.bam...                       ||
||    Paired-end reads are included.                                          ||
||    The reads are assigned on the single-end mode.                          ||
||    Total alignments : 60314777                                             ||
||    Successfully assigned alignments : 48274710 (80.0%)                     ||
||    Running time : 9.26 minutes                                             ||
||                                                                            ||
|| Write the final count table.                                               ||
|| Write the read assignment summary.                                         ||
||                                                                            ||
|| Summary of counting results can be found in file "outputs/featureCounts_o  ||
|| utputs/5dpi_HY_C57mouse_Lung.featurecounts.txt.summary"                    ||
||                                                                            ||
\\============================================================================//


        ==========     _____ _    _ ____  _____  ______          _____
        =====         / ____| |  | |  _ \|  __ \|  ____|   /\   |  __ \
          =====      | (___ | |  | | |_) | |__) | |__     /  \  | |  | |
            ====      \___ \| |  | |  _ <|  _  /|  __|   / /\ \ | |  | |
              ====    ____) | |__| | |_) | | \ \| |____ / ____ \| |__| |
        ==========   |_____/ \____/|____/|_|  \_\______/_/    \_\_____/
	  v2.0.6

//========================== featureCounts setting ===========================\\
||                                                                            ||
||             Input files : 1 BAM file                                       ||
||                                                                            ||
||                           3dpi_HY_C57mouse_Lung.sorted.bam                 ||
||                                                                            ||
||             Output file : 3dpi_HY_C57mouse_Lung.featurecounts.txt          ||
||                 Summary : 3dpi_HY_C57mouse_Lung.featurecounts.txt.summary  ||
||              Paired-end : yes                                              ||
||        Count read pairs : no                                               ||
||              Annotation : Mus_musculus.GRCm38.84.gtf (GTF)                 ||
||      Dir for temp files : outputs/featureCounts_outputs                    ||
||                                                                            ||
||                 Threads : 1                                                ||
||                   Level : meta-feature level                               ||
||      Multimapping reads : not counted                                      ||
|| Multi-overlapping reads : not counted                                      ||
||   Min overlapping bases : 1                                                ||
||                                                                            ||
\\============================================================================//

//================================= Running ==================================\\
||                                                                            ||
|| Load annotation file Mus_musculus.GRCm38.84.gtf ...                        ||

featureCounts -a assets/grcm38_tran/Mus_musculus.GRCm38.84.gtf -o outputs/featureCounts_outputs/3dpi_HY_C57mouse_Lung.featurecounts.txt -p -t exon -g gene_id outputs/hisat2_outputs/3dpi_HY_C57mouse_Lung.sorted.bam

||    Features : 710016                                                       ||
||    Meta-features : 47729                                                   ||
||    Chromosomes/contigs : 45                                                ||
||                                                                            ||
|| Process BAM file 3dpi_HY_C57mouse_Lung.sorted.bam...                       ||
||    Paired-end reads are included.                                          ||
||    The reads are assigned on the single-end mode.                          ||
||    Total alignments : 44393304                                             ||
||    Successfully assigned alignments : 35475677 (79.9%)                     ||
||    Running time : 9.15 minutes                                             ||
||                                                                            ||
|| Write the final count table.                                               ||
|| Write the read assignment summary.                                         ||
||                                                                            ||
|| Summary of counting results can be found in file "outputs/featureCounts_o  ||
|| utputs/3dpi_HY_C57mouse_Lung.featurecounts.txt.summary"                    ||
||                                                                            ||
\\============================================================================//


        ==========     _____ _    _ ____  _____  ______          _____
        =====         / ____| |  | |  _ \|  __ \|  ____|   /\   |  __ \
          =====      | (___ | |  | | |_) | |__) | |__     /  \  | |  | |
            ====      \___ \| |  | |  _ <|  _  /|  __|   / /\ \ | |  | |
              ====    ____) | |__| | |_) | | \ \| |____ / ____ \| |__| |
        ==========   |_____/ \____/|____/|_|  \_\______/_/    \_\_____/
	  v2.0.6

//========================== featureCounts setting ===========================\\
||                                                                            ||
||             Input files : 1 BAM file                                       ||
||                                                                            ||
||                           5dpi_T7_C57mouse_Lung.sorted.bam                 ||
||                                                                            ||
||             Output file : 5dpi_T7_C57mouse_Lung.featurecounts.txt          ||
||                 Summary : 5dpi_T7_C57mouse_Lung.featurecounts.txt.summary  ||
||              Paired-end : yes                                              ||
||        Count read pairs : no                                               ||
||              Annotation : Mus_musculus.GRCm38.84.gtf (GTF)                 ||
||      Dir for temp files : outputs/featureCounts_outputs                    ||
||                                                                            ||
||                 Threads : 1                                                ||
||                   Level : meta-feature level                               ||
||      Multimapping reads : not counted                                      ||
|| Multi-overlapping reads : not counted                                      ||
||   Min overlapping bases : 1                                                ||
||                                                                            ||
\\============================================================================//

//================================= Running ==================================\\
||                                                                            ||
|| Load annotation file Mus_musculus.GRCm38.84.gtf ...                        ||

featureCounts -a assets/grcm38_tran/Mus_musculus.GRCm38.84.gtf -o outputs/featureCounts_outputs/5dpi_T7_C57mouse_Lung.featurecounts.txt -p -t exon -g gene_id outputs/hisat2_outputs/5dpi_T7_C57mouse_Lung.sorted.bam

||    Features : 710016                                                       ||
||    Meta-features : 47729                                                   ||
||    Chromosomes/contigs : 45                                                ||
||                                                                            ||
|| Process BAM file 5dpi_T7_C57mouse_Lung.sorted.bam...                       ||
||    Paired-end reads are included.                                          ||
||    The reads are assigned on the single-end mode.                          ||
||    Total alignments : 52247544                                             ||
||    Successfully assigned alignments : 39733026 (76.0%)                     ||
||    Running time : 8.81 minutes                                             ||
||                                                                            ||
|| Write the final count table.                                               ||
|| Write the read assignment summary.                                         ||
||                                                                            ||
|| Summary of counting results can be found in file "outputs/featureCounts_o  ||
|| utputs/5dpi_T7_C57mouse_Lung.featurecounts.txt.summary"                    ||
||                                                                            ||
\\============================================================================//

featureCounts -a assets/grcm38_tran/Mus_musculus.GRCm38.84.gtf -o outputs/featureCounts_outputs/5dpi_0_C57mouse_Lung.featurecounts.txt -p -t exon -g gene_id outputs/hisat2_outputs/5dpi_0_C57mouse_Lung.sorted.bam

        ==========     _____ _    _ ____  _____  ______          _____
        =====         / ____| |  | |  _ \|  __ \|  ____|   /\   |  __ \
          =====      | (___ | |  | | |_) | |__) | |__     /  \  | |  | |
            ====      \___ \| |  | |  _ <|  _  /|  __|   / /\ \ | |  | |
              ====    ____) | |__| | |_) | | \ \| |____ / ____ \| |__| |
        ==========   |_____/ \____/|____/|_|  \_\______/_/    \_\_____/
	  v2.0.6

//========================== featureCounts setting ===========================\\
||                                                                            ||
||             Input files : 1 BAM file                                       ||
||                                                                            ||
||                           5dpi_0_C57mouse_Lung.sorted.bam                  ||
||                                                                            ||
||             Output file : 5dpi_0_C57mouse_Lung.featurecounts.txt           ||
||                 Summary : 5dpi_0_C57mouse_Lung.featurecounts.txt.summary   ||
||              Paired-end : yes                                              ||
||        Count read pairs : no                                               ||
||              Annotation : Mus_musculus.GRCm38.84.gtf (GTF)                 ||
||      Dir for temp files : outputs/featureCounts_outputs                    ||
||                                                                            ||
||                 Threads : 1                                                ||
||                   Level : meta-feature level                               ||
||      Multimapping reads : not counted                                      ||
|| Multi-overlapping reads : not counted                                      ||
||   Min overlapping bases : 1                                                ||
||                                                                            ||
\\============================================================================//

//================================= Running ==================================\\
||                                                                            ||
|| Load annotation file Mus_musculus.GRCm38.84.gtf ...                        ||
||    Features : 710016                                                       ||
||    Meta-features : 47729                                                   ||
||    Chromosomes/contigs : 45                                                ||
||                                                                            ||
|| Process BAM file 5dpi_0_C57mouse_Lung.sorted.bam...                        ||
||    Paired-end reads are included.                                          ||
||    The reads are assigned on the single-end mode.                          ||
||    Total alignments : 44488675                                             ||
||    Successfully assigned alignments : 35001770 (78.7%)                     ||
||    Running time : 6.86 minutes                                             ||
||                                                                            ||
|| Write the final count table.                                               ||
|| Write the read assignment summary.                                         ||
||                                                                            ||
|| Summary of counting results can be found in file "outputs/featureCounts_o  ||
|| utputs/5dpi_0_C57mouse_Lung.featurecounts.txt.summary"                     ||
||                                                                            ||
\\============================================================================//


        ==========     _____ _    _ ____  _____  ______          _____
        =====         / ____| |  | |  _ \|  __ \|  ____|   /\   |  __ \
          =====      | (___ | |  | | |_) | |__) | |__     /  \  | |  | |
            ====      \___ \| |  | |  _ <|  _  /|  __|   / /\ \ | |  | |
              ====    ____) | |__| | |_) | | \ \| |____ / ____ \| |__| |
        ==========   |_____/ \____/|____/|_|  \_\______/_/    \_\_____/
	  v2.0.6

//========================== featureCounts setting ===========================\\
||                                                                            ||
||             Input files : 1 BAM file                                       ||
||                                                                            ||
||                           3dpi_T7_C57mouse_Lung.sorted.bam                 ||
||                                                                            ||
||             Output file : 3dpi_T7_C57mouse_Lung.featurecounts.txt          ||
||                 Summary : 3dpi_T7_C57mouse_Lung.featurecounts.txt.summary  ||
||              Paired-end : yes                                              ||
||        Count read pairs : no                                               ||
||              Annotation : Mus_musculus.GRCm38.84.gtf (GTF)                 ||
||      Dir for temp files : outputs/featureCounts_outputs                    ||
||                                                                            ||
||                 Threads : 1                                                ||
||                   Level : meta-feature level                               ||
||      Multimapping reads : not counted                                      ||
|| Multi-overlapping reads : not counted                                      ||
||   Min overlapping bases : 1                                                ||
||                                                                            ||
\\============================================================================//

//================================= Running ==================================\\
||                                                                            ||
|| Load annotation file Mus_musculus.GRCm38.84.gtf ...                        ||

featureCounts -a assets/grcm38_tran/Mus_musculus.GRCm38.84.gtf -o outputs/featureCounts_outputs/3dpi_T7_C57mouse_Lung.featurecounts.txt -p -t exon -g gene_id outputs/hisat2_outputs/3dpi_T7_C57mouse_Lung.sorted.bam

||    Features : 710016                                                       ||
||    Meta-features : 47729                                                   ||
||    Chromosomes/contigs : 45                                                ||
||                                                                            ||
|| Process BAM file 3dpi_T7_C57mouse_Lung.sorted.bam...                       ||
||    Paired-end reads are included.                                          ||
||    The reads are assigned on the single-end mode.                          ||
||    Total alignments : 45242173                                             ||
||    Successfully assigned alignments : 35448318 (78.4%)                     ||
||    Running time : 7.33 minutes                                             ||
||                                                                            ||
|| Write the final count table.                                               ||
|| Write the read assignment summary.                                         ||
||                                                                            ||
|| Summary of counting results can be found in file "outputs/featureCounts_o  ||
|| utputs/3dpi_T7_C57mouse_Lung.featurecounts.txt.summary"                    ||
||                                                                            ||
\\============================================================================//


        ==========     _____ _    _ ____  _____  ______          _____
        =====         / ____| |  | |  _ \|  __ \|  ____|   /\   |  __ \
          =====      | (___ | |  | | |_) | |__) | |__     /  \  | |  | |
            ====      \___ \| |  | |  _ <|  _  /|  __|   / /\ \ | |  | |
              ====    ____) | |__| | |_) | | \ \| |____ / ____ \| |__| |
        ==========   |_____/ \____/|____/|_|  \_\______/_/    \_\_____/
	  v2.0.6

//========================== featureCounts setting ===========================\\
||                                                                            ||
||             Input files : 1 BAM file                                       ||
||                                                                            ||
||                           3dpi_0_C57mouse_Lung.sorted.bam                  ||
||                                                                            ||
||             Output file : 3dpi_0_C57mouse_Lung.featurecounts.txt           ||
||                 Summary : 3dpi_0_C57mouse_Lung.featurecounts.txt.summary   ||
||              Paired-end : yes                                              ||
||        Count read pairs : no                                               ||
||              Annotation : Mus_musculus.GRCm38.84.gtf (GTF)                 ||
||      Dir for temp files : outputs/featureCounts_outputs                    ||
||                                                                            ||
||                 Threads : 1                                                ||
||                   Level : meta-feature level                               ||
||      Multimapping reads : not counted                                      ||
|| Multi-overlapping reads : not counted                                      ||
||   Min overlapping bases : 1                                                ||
||                                                                            ||
\\============================================================================//

//================================= Running ==================================\\
||                                                                            ||
|| Load annotation file Mus_musculus.GRCm38.84.gtf ...                        ||

featureCounts -a assets/grcm38_tran/Mus_musculus.GRCm38.84.gtf -o outputs/featureCounts_outputs/3dpi_0_C57mouse_Lung.featurecounts.txt -p -t exon -g gene_id outputs/hisat2_outputs/3dpi_0_C57mouse_Lung.sorted.bam

||    Features : 710016                                                       ||
||    Meta-features : 47729                                                   ||
||    Chromosomes/contigs : 45                                                ||
||                                                                            ||
|| Process BAM file 3dpi_0_C57mouse_Lung.sorted.bam...                        ||
||    Paired-end reads are included.                                          ||
||    The reads are assigned on the single-end mode.                          ||
||    Total alignments : 66806874                                             ||
||    Successfully assigned alignments : 45494635 (68.1%)                     ||
||    Running time : 9.07 minutes                                             ||
||                                                                            ||
|| Write the final count table.                                               ||
|| Write the read assignment summary.                                         ||
||                                                                            ||
|| Summary of counting results can be found in file "outputs/featureCounts_o  ||
|| utputs/3dpi_0_C57mouse_Lung.featurecounts.txt.summary"                     ||
||                                                                            ||
\\============================================================================//

featureCounts -a assets/grcm38_tran/Mus_musculus.GRCm38.84.gtf -o outputs/featureCounts_outputs/3dpi_N289D_C57mouse_Lung.featurecounts.txt -p -t exon -g gene_id outputs/hisat2_outputs/3dpi_N289D_C57mouse_Lung.sorted.bam

        ==========     _____ _    _ ____  _____  ______          _____
        =====         / ____| |  | |  _ \|  __ \|  ____|   /\   |  __ \
          =====      | (___ | |  | | |_) | |__) | |__     /  \  | |  | |
            ====      \___ \| |  | |  _ <|  _  /|  __|   / /\ \ | |  | |
              ====    ____) | |__| | |_) | | \ \| |____ / ____ \| |__| |
        ==========   |_____/ \____/|____/|_|  \_\______/_/    \_\_____/
	  v2.0.6

//========================== featureCounts setting ===========================\\
||                                                                            ||
||             Input files : 1 BAM file                                       ||
||                                                                            ||
||                           3dpi_N289D_C57mouse_Lung.sorted.bam              ||
||                                                                            ||
||             Output file : 3dpi_N289D_C57mouse_Lung.featurecounts.txt       ||
||                 Summary : 3dpi_N289D_C57mouse_Lung.featurecounts.txt.s ... ||
||              Paired-end : yes                                              ||
||        Count read pairs : no                                               ||
||              Annotation : Mus_musculus.GRCm38.84.gtf (GTF)                 ||
||      Dir for temp files : outputs/featureCounts_outputs                    ||
||                                                                            ||
||                 Threads : 1                                                ||
||                   Level : meta-feature level                               ||
||      Multimapping reads : not counted                                      ||
|| Multi-overlapping reads : not counted                                      ||
||   Min overlapping bases : 1                                                ||
||                                                                            ||
\\============================================================================//

//================================= Running ==================================\\
||                                                                            ||
|| Load annotation file Mus_musculus.GRCm38.84.gtf ...                        ||
||    Features : 710016                                                       ||
||    Meta-features : 47729                                                   ||
||    Chromosomes/contigs : 45                                                ||
||                                                                            ||
|| Process BAM file 3dpi_N289D_C57mouse_Lung.sorted.bam...                    ||
||    Paired-end reads are included.                                          ||
||    The reads are assigned on the single-end mode.                          ||
||    Total alignments : 57362577                                             ||
||    Successfully assigned alignments : 44924013 (78.3%)                     ||
||    Running time : 7.30 minutes                                             ||
||                                                                            ||
|| Write the final count table.                                               ||
|| Write the read assignment summary.                                         ||
||                                                                            ||
|| Summary of counting results can be found in file "outputs/featureCounts_o  ||
|| utputs/3dpi_N289D_C57mouse_Lung.featurecounts.txt.summary"                 ||
||                                                                            ||
\\============================================================================//

featureCounts -a assets/grcm38_tran/Mus_musculus.GRCm38.84.gtf -o outputs/featureCounts_outputs/5dpi_KT_C57mouse_Lung.featurecounts.txt -p -t exon -g gene_id outputs/hisat2_outputs/5dpi_KT_C57mouse_Lung.sorted.bam

        ==========     _____ _    _ ____  _____  ______          _____
        =====         / ____| |  | |  _ \|  __ \|  ____|   /\   |  __ \
          =====      | (___ | |  | | |_) | |__) | |__     /  \  | |  | |
            ====      \___ \| |  | |  _ <|  _  /|  __|   / /\ \ | |  | |
              ====    ____) | |__| | |_) | | \ \| |____ / ____ \| |__| |
        ==========   |_____/ \____/|____/|_|  \_\______/_/    \_\_____/
	  v2.0.6

//========================== featureCounts setting ===========================\\
||                                                                            ||
||             Input files : 1 BAM file                                       ||
||                                                                            ||
||                           5dpi_KT_C57mouse_Lung.sorted.bam                 ||
||                                                                            ||
||             Output file : 5dpi_KT_C57mouse_Lung.featurecounts.txt          ||
||                 Summary : 5dpi_KT_C57mouse_Lung.featurecounts.txt.summary  ||
||              Paired-end : yes                                              ||
||        Count read pairs : no                                               ||
||              Annotation : Mus_musculus.GRCm38.84.gtf (GTF)                 ||
||      Dir for temp files : outputs/featureCounts_outputs                    ||
||                                                                            ||
||                 Threads : 1                                                ||
||                   Level : meta-feature level                               ||
||      Multimapping reads : not counted                                      ||
|| Multi-overlapping reads : not counted                                      ||
||   Min overlapping bases : 1                                                ||
||                                                                            ||
\\============================================================================//

//================================= Running ==================================\\
||                                                                            ||
|| Load annotation file Mus_musculus.GRCm38.84.gtf ...                        ||
||    Features : 710016                                                       ||
||    Meta-features : 47729                                                   ||
||    Chromosomes/contigs : 45                                                ||
||                                                                            ||
|| Process BAM file 5dpi_KT_C57mouse_Lung.sorted.bam...                       ||
||    Paired-end reads are included.                                          ||
||    The reads are assigned on the single-end mode.                          ||
||    Total alignments : 59176993                                             ||
||    Successfully assigned alignments : 46149004 (78.0%)                     ||
||    Running time : 7.35 minutes                                             ||
||                                                                            ||
|| Write the final count table.                                               ||
|| Write the read assignment summary.                                         ||
||                                                                            ||
|| Summary of counting results can be found in file "outputs/featureCounts_o  ||
|| utputs/5dpi_KT_C57mouse_Lung.featurecounts.txt.summary"                    ||
||                                                                            ||
\\============================================================================//

In [345]:
rsem_script_path = '/home/chenrujian/RSEM-1.3.3'

In [394]:
# 构建索引
genome_fa = 'assets/mus_genome/data/GCF_000001635.27/GCF_000001635.27_GRCm39_genomic.fna'
annotation_gtf = 'assets/mus_annotations/GCF_000001635.27/genomic.gtf'
reference_name = 'GRCm39_genomic_reference'

rsem_build = f'{rsem_script_path}/rsem-prepare-reference -p 40 \
--gtf {annotation_gtf} \
{genome_fa} {reference_name}'

print(rsem_build)
os.system(rsem_build)

/home/chenrujian/RSEM-1.3.3/rsem-prepare-reference -p 40 --gtf assets/mus_annotations/GCF_000001635.27/genomic.gtf assets/mus_genome/data/GCF_000001635.27/GCF_000001635.27_GRCm39_genomic.fna GRCm39_genomic_reference
rsem-extract-reference-transcripts GRCm39_genomic_reference 0 assets/mus_annotations/GCF_000001635.27/genomic.gtf None 0 assets/mus_genome/data/GCF_000001635.27/GCF_000001635.27_GRCm39_genomic.fna
Parsed 200000 lines
Parsed 400000 lines
Parsed 600000 lines
Parsed 800000 lines
Parsed 1000000 lines
Parsed 1200000 lines
Parsed 1400000 lines
Parsed 1600000 lines
Parsed 1800000 lines
Parsed 2000000 lines
Parsed 2200000 lines
Parsed 2400000 lines
Parsed 2600000 lines
Parsed 2800000 lines
Parsed 3000000 lines
Parsing gtf File is done!
assets/mus_genome/data/GCF_000001635.27/GCF_000001635.27_GRCm39_genomic.fna is processed!
137925 transcripts are extracted.
Extracting sequences is done!
Group File is generated!
Transcript Information File is generated!
Chromosome List File is generated!
Extracted Sequences File is generated!

rsem-preref GRCm39_genomic_reference.transcripts.fa 1 GRCm39_genomic_reference
Refs.makeRefs finished!
Refs.saveRefs finished!
GRCm39_genomic_reference.idx.fa is generated!
GRCm39_genomic_reference.n2g.idx.fa is generated!

0

In [380]:
upstream_read_bams = []

for sample in os.listdir('outputs/hisat2_outputs'):
    if not sample.endswith(".bam"):
        continue
    p = f'outputs/hisat2_outputs/{sample}'
    upstream_read_bams.append(p)
    
upstream_read_bams

['outputs/hisat2_outputs/3dpi_HY_C57mouse_Lung.hisat2.bam',
 'outputs/hisat2_outputs/5dpi_T7_C57mouse_Lung.hisat2.bam',
 'outputs/hisat2_outputs/5dpi_KT_C57mouse_Lung.hisat2.bam',
 'outputs/hisat2_outputs/3dpi_T7_C57mouse_Lung.hisat2.bam',
 'outputs/hisat2_outputs/3dpi_KT_C57mouse_Lung.hisat2.bam',
 'outputs/hisat2_outputs/5dpi_0_C57mouse_Lung.hisat2.bam',
 'outputs/hisat2_outputs/5dpi_N289D_C57mouse_Lung.hisat2.bam',
 'outputs/hisat2_outputs/3dpi_N289D_C57mouse_Lung.hisat2.bam',
 'outputs/hisat2_outputs/3dpi_0_C57mouse_Lung.hisat2.bam',
 'outputs/hisat2_outputs/5dpi_HY_C57mouse_Lung.hisat2.bam']

In [382]:
upstream_read_bams = ['outputs/hisat2_outputs/3dpi_HY_C57mouse_Lung.hisat2.bam',
 'outputs/hisat2_outputs/5dpi_T7_C57mouse_Lung.hisat2.bam',
 'outputs/hisat2_outputs/5dpi_KT_C57mouse_Lung.hisat2.bam',
 'outputs/hisat2_outputs/3dpi_T7_C57mouse_Lung.hisat2.bam',
 'outputs/hisat2_outputs/3dpi_KT_C57mouse_Lung.hisat2.bam',
 #'outputs/hisat2_outputs/5dpi_0_C57mouse_Lung.hisat2.bam',
 'outputs/hisat2_outputs/5dpi_N289D_C57mouse_Lung.hisat2.bam',
 'outputs/hisat2_outputs/3dpi_N289D_C57mouse_Lung.hisat2.bam',
 'outputs/hisat2_outputs/3dpi_0_C57mouse_Lung.hisat2.bam',
 'outputs/hisat2_outputs/5dpi_HY_C57mouse_Lung.hisat2.bam']
with open('bam_paths.txt', 'w') as f:
    for bam in upstream_read_bams:
        f.write(f'{bam}\n')

In [ ]:
upstream_read_bams = 'bam_paths.txt'

reference_name = 'GRCm39_genomic_reference'

out_prefix = 'outputs/rsem'

rsem_calculate = f'{rsem_script_path}/rsem-calculate-expression -p 40 \
--hisat2-hca \
--hisat2-path /home/chenrujian/anaconda3/bin/hisat2 \
--paired-end -no-bam-output --alignments \
--bam {upstream_read_bams} {reference_name} {out_prefix}'

print(rsem_calculate)
os.system(rsem_calculate)

/home/chenrujian/RSEM-1.3.3/rsem-calculate-expression -p 40 --hisat2-hca --hisat2-path /home/chenrujian/anaconda3/bin/hisat2 --paired-end -no-bam-output --alignments --bam bam_paths.txt GRCm39_genomic_reference outputs/rsem
rsem-parse-alignments GRCm39_genomic_reference outputs/rsem.temp/rsem outputs/rsem.stat/rsem bam_paths.txt 3 -tag XM
"rsem-parse-alignments GRCm39_genomic_reference outputs/rsem.temp/rsem outputs/rsem.stat/rsem bam_paths.txt 3 -tag XM" failed! Plase check if you provide correct parameters/options for the pipeline!

The SAM/BAM file declares less than one reference sequence!

65280

In [350]:
!/home/chenrujian/RSEM-1.3.3/rsem-calculate-expression --help

NAME
    rsem-calculate-expression - Estimate gene and isoform expression from
    RNA-Seq data.

SYNOPSIS
     rsem-calculate-expression [options] upstream_read_file(s) reference_name sample_name
     rsem-calculate-expression [options] --paired-end upstream_read_file(s) downstream_read_file(s) reference_name sample_name
     rsem-calculate-expression [options] --alignments [--paired-end] input reference_name sample_name

ARGUMENTS
    upstream_read_files(s)
        Comma-separated list of files containing single-end reads or
        upstream reads for paired-end data. By default, these files are
        assumed to be in FASTQ format. If the --no-qualities option is
        specified, then FASTA format is expected.

    downstream_read_file(s)
        Comma-separated list of files containing downstream reads which are
        paired with the upstream reads. By default, these files are assumed
        to be in FASTQ format. If the --no-qualities option is specified,
        then FASTA format is expected.

    input
        SAM/BAM/CRAM formatted input file. If "-" is specified for the
        filename, the input is instead assumed to come from standard input.
        RSEM requires all alignments of the same read group together. For
        paired-end reads, RSEM also requires the two mates of any alignment
        be adjacent. In addition, RSEM does not allow the SEQ and QUAL
        fields to be empty. See Description section for how to make input
        file obey RSEM's requirements.

    reference_name
        The name of the reference used. The user must have run
        'rsem-prepare-reference' with this reference_name before running
        this program.

    sample_name
        The name of the sample analyzed. All output files are prefixed by
        this name (e.g., sample_name.genes.results)

BASIC OPTIONS
    --paired-end
        Input reads are paired-end reads. (Default: off)

    --no-qualities
        Input reads do not contain quality scores. (Default: off)

    --strandedness <none|forward|reverse>
        This option defines the strandedness of the RNA-Seq reads. It
        recognizes three values: 'none', 'forward', and 'reverse'. 'none'
        refers to non-strand-specific protocols. 'forward' means all
        (upstream) reads are derived from the forward strand. 'reverse'
        means all (upstream) reads are derived from the reverse strand. If
        'forward'/'reverse' is set, the '--norc'/'--nofw' Bowtie/Bowtie 2
        option will also be enabled to avoid aligning reads to the opposite
        strand. For Illumina TruSeq Stranded protocols, please use
        'reverse'. (Default: 'none')

    -p/--num-threads <int>
        Number of threads to use. Both Bowtie/Bowtie2, expression estimation
        and 'samtools sort' will use this many threads. (Default: 1)

    --alignments
        Input file contains alignments in SAM/BAM/CRAM format. The exact
        file format will be determined automatically. (Default: off)

    --fai <file>
        If the header section of input alignment file does not contain
        reference sequence information, this option should be turned on.
        <file> is a FAI format file containing each reference sequence's
        name and length. Please refer to the SAM official website for the
        details of FAI format. (Default: off)

    --bowtie2
        Use Bowtie 2 instead of Bowtie to align reads. Since currently RSEM
        does not handle indel, local and discordant alignments, the Bowtie2
        parameters are set in a way to avoid those alignments. In
        particular, we use options '--sensitive --dpad 0 --gbar 99999999
        --mp 1,1 --np 1 --score-min L,0,-0.1' by default. The last parameter
        of '--score-min', '-0.1', is the negative of maximum mismatch rate.
        This rate can be set by option '--bowtie2-mismatch-rate'. If reads
        are paired-end, we additionally use options '--no-mixed' and
        '--no-discordant'. (Default: off)

    --star
        Use STAR to align reads. Alignment parameters are from ENCODE3's
        STAR-RSEM pipeline. To save computational time and memory resources,
        STAR's Output BAM file is unsorted. It is stored in RSEM's temporary
        directory with name as 'sample_name.bam'. Each STAR job will have
        its own private copy of the genome in memory. (Default: off)

    --hisat2-hca
        Use HISAT2 to align reads to the transcriptome according to Human
        Cell Atlast SMART-Seq2 pipeline. In particular, we use HISAT
        parameters "-k 10 --secondary --rg-id=$sampleToken --rg
        SM:$sampleToken --rg LB:$sampleToken --rg PL:ILLUMINA --rg
        PU:$sampleToken --new-summary --summary-file $sampleName.log
        --met-file $sampleName.hisat2.met.txt --met 5 --mp 1,1 --np 1
        --score-min L,0,-0.1 --rdg 99999999,99999999 --rfg 99999999,99999999
        --no-spliced-alignment --no-softclip --seed 12345". If inputs are
        paired-end reads, we additionally use parameters "--no-mixed
        --no-discordant". (Default: off)

    --append-names
        If gene_name/transcript_name is available, append it to the end of
        gene_id/transcript_id (separated by '_') in files
        'sample_name.isoforms.results' and 'sample_name.genes.results'.
        (Default: off)

    --seed <uint32>
        Set the seed for the random number generators used in calculating
        posterior mean estimates and credibility intervals. The seed must be
        a non-negative 32 bit integer. (Default: off)

    --single-cell-prior
        By default, RSEM uses Dirichlet(1) as the prior to calculate
        posterior mean estimates and credibility intervals. However, much
        less genes are expressed in single cell RNA-Seq data. Thus, if you
        want to compute posterior mean estimates and/or credibility
        intervals and you have single-cell RNA-Seq data, you are recommended
        to turn on this option. Then RSEM will use Dirichlet(0.1) as the
        prior which encourage the sparsity of the expression levels.
        (Default: off)

    --calc-pme
        Run RSEM's collapsed Gibbs sampler to calculate posterior mean
        estimates. (Default: off)

    --calc-ci
        Calculate 95% credibility intervals and posterior mean estimates.
        The credibility level can be changed by setting
        '--ci-credibility-level'. (Default: off)

    -q/--quiet
        Suppress the output of logging information. (Default: off)

    -h/--help
        Show help information.

    --version
        Show version information.

OUTPUT OPTIONS
    --sort-bam-by-read-name
        Sort BAM file aligned under transcript coordidate by read name.
        Setting this option on will produce deterministic maximum likelihood
        estimations from independent runs. Note that sorting will take long
        time and lots of memory. (Default: off)

    --no-bam-output
        Do not output any BAM file. (Default: off)

    --sampling-for-bam
        When RSEM generates a BAM file, instead of outputting all alignments
        a read has with their posterior probabilities, one alignment is
        sampled according to the posterior probabilities. The sampling
        procedure includes the alignment to the "noise" transcript, which
        does not appear in the BAM file. Only the sampled alignment has a
        weight of 1. All other alignments have weight 0. If the "noise"
        transcript is sampled, all alignments appeared in the BAM file
        should have weight 0. (Default: off)

    --output-genome-bam
        Generate a BAM file, 'sample_name.genome.bam', with alignments
        mapped to genomic coordinates and annotated with their posterior
        probabilities. In addition, RSEM will call samtools (included in
        RSEM package) to sort and index the bam file.
        'sample_name.genome.sorted.bam' and
        'sample_name.genome.sorted.bam.bai' will be generated. (Default:
        off)

    --sort-bam-by-coordinate
        Sort RSEM generated transcript and genome BAM files by coordinates
        and build associated indices. (Default: off)

    --sort-bam-memory-per-thread <string>
        Set the maximum memory per thread that can be used by 'samtools
        sort'. <string> represents the memory and accepts suffices 'K/M/G'.
        RSEM will pass <string> to the '-m' option of 'samtools sort'. Note
        that the default used here is different from the default used by
        samtools. (Default: 1G)

ALIGNER OPTIONS
    --seed-length <int>
        Seed length used by the read aligner. Providing the correct value is
        important for RSEM. If RSEM runs Bowtie, it uses this value for
        Bowtie's seed length parameter. Any read with its or at least one of
        its mates' (for paired-end reads) length less than this value will
        be ignored. If the references are not added poly(A) tails, the
        minimum allowed value is 5, otherwise, the minimum allowed value is
        25. Note that this script will only check if the value >= 5 and give
        a warning message if the value < 25 but >= 5. (Default: 25)

    --phred33-quals
        Input quality scores are encoded as Phred+33. This option is used by
        Bowtie, Bowtie 2 and HISAT2. (Default: on)

    --phred64-quals
        Input quality scores are encoded as Phred+64 (default for GA
        Pipeline ver. >= 1.3). This option is used by Bowtie, Bowtie 2 and
        HISAT2. (Default: off)

    --solexa-quals
        Input quality scores are solexa encoded (from GA Pipeline ver. <
        1.3). This option is used by Bowtie, Bowtie 2 and HISAT2. (Default:
        off)

    --bowtie-path <path>
        The path to the Bowtie executables. (Default: the path to the Bowtie
        executables is assumed to be in the user's PATH environment
        variable)

    --bowtie-n <int>
        (Bowtie parameter) max # of mismatches in the seed. (Range: 0-3,
        Default: 2)

    --bowtie-e <int>
        (Bowtie parameter) max sum of mismatch quality scores across the
        alignment. (Default: 99999999)

    --bowtie-m <int>
        (Bowtie parameter) suppress all alignments for a read if > <int>
        valid alignments exist. (Default: 200)

    --bowtie-chunkmbs <int>
        (Bowtie parameter) memory allocated for best first alignment
        calculation (Default: 0 - use Bowtie's default)

    --bowtie2-path <path>
        (Bowtie 2 parameter) The path to the Bowtie 2 executables. (Default:
        the path to the Bowtie 2 executables is assumed to be in the user's
        PATH environment variable)

    --bowtie2-mismatch-rate <double>
        (Bowtie 2 parameter) The maximum mismatch rate allowed. (Default:
        0.1)

    --bowtie2-k <int>
        (Bowtie 2 parameter) Find up to <int> alignments per read. (Default:
        200)

    --bowtie2-sensitivity-level <string>
        (Bowtie 2 parameter) Set Bowtie 2's preset options in --end-to-end
        mode. This option controls how hard Bowtie 2 tries to find
        alignments. <string> must be one of "very_fast", "fast", "sensitive"
        and "very_sensitive". The four candidates correspond to Bowtie 2's
        "--very-fast", "--fast", "--sensitive" and "--very-sensitive"
        options. (Default: "sensitive" - use Bowtie 2's default)

    --star-path <path>
        The path to STAR's executable. (Default: the path to STAR executable
        is assumed to be in user's PATH environment variable)

    --star-gzipped-read-file
        (STAR parameter) Input read file(s) is compressed by gzip. (Default:
        off)

    --star-bzipped-read-file
        (STAR parameter) Input read file(s) is compressed by bzip2.
        (Default: off)

    --star-output-genome-bam
        (STAR parameter) Save the BAM file from STAR alignment under genomic
        coordinate to 'sample_name.STAR.genome.bam'. This file is NOT sorted
        by genomic coordinate. In this file, according to STAR's manual,
        'paired ends of an alignment are always adjacent, and multiple
        alignments of a read are adjacent as well'. (Default: off)

    --hisat2-path <path>
        The path to HISAT2's executable. (Default: the path to HISAT2
        executable is assumed to be in user's PATH environment variable)

ADVANCED OPTIONS
    --tag <string>
        The name of the optional field used in the SAM input for identifying
        a read with too many valid alignments. The field should have the
        format <tagName>:i:<value>, where a <value> bigger than 0 indicates
        a read with too many alignments. (Default: "")

    --fragment-length-min <int>
        Minimum read/insert length allowed. This is also the value for the
        Bowtie/Bowtie2 -I option. (Default: 1)

    --fragment-length-max <int>
        Maximum read/insert length allowed. This is also the value for the
        Bowtie/Bowtie 2 -X option. (Default: 1000)

    --fragment-length-mean <double>
        (single-end data only) The mean of the fragment length distribution,
        which is assumed to be a Gaussian. (Default: -1, which disables use
        of the fragment length distribution)

    --fragment-length-sd <double>
        (single-end data only) The standard deviation of the fragment length
        distribution, which is assumed to be a Gaussian. (Default: 0, which
        assumes that all fragments are of the same length, given by the
        rounded value of --fragment-length-mean)

    --estimate-rspd
        Set this option if you want to estimate the read start position
        distribution (RSPD) from data. Otherwise, RSEM will use a uniform
        RSPD. (Default: off)

    --num-rspd-bins <int>
        Number of bins in the RSPD. Only relevant when '--estimate-rspd' is
        specified. Use of the default setting is recommended. (Default: 20)

    --gibbs-burnin <int>
        The number of burn-in rounds for RSEM's Gibbs sampler. Each round
        passes over the entire data set once. If RSEM can use multiple
        threads, multiple Gibbs samplers will start at the same time and all
        samplers share the same burn-in number. (Default: 200)

    --gibbs-number-of-samples <int>
        The total number of count vectors RSEM will collect from its Gibbs
        samplers. (Default: 1000)

    --gibbs-sampling-gap <int>
        The number of rounds between two succinct count vectors RSEM
        collects. If the count vector after round N is collected, the count
        vector after round N + <int> will also be collected. (Default: 1)

    --ci-credibility-level <double>
        The credibility level for credibility intervals. (Default: 0.95)

    --ci-memory <int>
        Maximum size (in memory, MB) of the auxiliary buffer used for
        computing credibility intervals (CI). (Default: 1024)

    --ci-number-of-samples-per-count-vector <int>
        The number of read generating probability vectors sampled per
        sampled count vector. The crebility intervals are calculated by
        first sampling P(C | D) and then sampling P(Theta | C) for each
        sampled count vector. This option controls how many Theta vectors
        are sampled per sampled count vector. (Default: 50)

    --keep-intermediate-files
        Keep temporary files generated by RSEM. RSEM creates a temporary
        directory, 'sample_name.temp', into which it puts all intermediate
        output files. If this directory already exists, RSEM overwrites all
        files generated by previous RSEM runs inside of it. By default,
        after RSEM finishes, the temporary directory is deleted. Set this
        option to prevent the deletion of this directory and the
        intermediate files inside of it. (Default: off)

    --temporary-folder <string>
        Set where to put the temporary files generated by RSEM. If the
        folder specified does not exist, RSEM will try to create it.
        (Default: sample_name.temp)

    --time
        Output time consumed by each step of RSEM to 'sample_name.time'.
        (Default: off)

PRIOR-ENHANCED RSEM OPTIONS
    --run-pRSEM
        Running prior-enhanced RSEM (pRSEM). Prior parameters, i.e.
        isoform's initial pseudo-count for RSEM's Gibbs sampling, will be
        learned from input RNA-seq data and an external data set. When pRSEM
        needs and only needs ChIP-seq peak information to partition isoforms
        (e.g. in pRSEM's default partition model), either ChIP-seq peak file
        (with the '--chipseq-peak-file' option) or ChIP-seq FASTQ files for
        target and input and the path for Bowtie executables are required
        (with the '--chipseq-target-read-files <string>',
        '--chipseq-control-read-files <string>', and '--bowtie-path <path>
        options), otherwise, ChIP-seq FASTQ files for target and control and
        the path to Bowtie executables are required. (Default: off)

    --chipseq-peak-file <string>
        Full path to a ChIP-seq peak file in ENCODE's narrowPeak, i.e.
        BED6+4, format. This file is used when running prior-enhanced RSEM
        in the default two-partition model. It partitions isoforms by
        whether they have ChIP-seq overlapping with their transcription
        start site region or not. Each partition will have its own prior
        parameter learned from a training set. This file can be either
        gzipped or ungzipped. (Default: "")

    --chipseq-target-read-files <string>
        Comma-separated full path of FASTQ read file(s) for ChIP-seq target.
        This option is used when running prior-enhanced RSEM. It provides
        information to calculate ChIP-seq peaks and signals. The file(s) can
        be either ungzipped or gzipped with a suffix '.gz' or '.gzip'. The
        options '--bowtie-path <path>' and '--chipseq-control-read-files
        <string>' must be defined when this option is specified. (Default:
        "")

    --chipseq-control-read-files <string>
        Comma-separated full path of FASTQ read file(s) for ChIP-seq conrol.
        This option is used when running prior-enhanced RSEM. It provides
        information to call ChIP-seq peaks. The file(s) can be either
        ungzipped or gzipped with a suffix '.gz' or '.gzip'. The options
        '--bowtie-path <path>' and '--chipseq-target-read-files <string>'
        must be defined when this option is specified. (Default: "")

    --chipseq-read-files-multi-targets <string>
        Comma-separated full path of FASTQ read files for multiple ChIP-seq
        targets. This option is used when running prior-enhanced RSEM, where
        prior is learned from multiple complementary data sets. It provides
        information to calculate ChIP-seq signals. All files can be either
        ungzipped or gzipped with a suffix '.gz' or '.gzip'. When this
        option is specified, the option '--bowtie-path <path>' must be
        defined and the option '--partition-model <string>' will be set to
        'cmb_lgt' automatically. (Default: "")

    --chipseq-bed-files-multi-targets <string>
        Comma-separated full path of BED files for multiple ChIP-seq
        targets. This option is used when running prior-enhanced RSEM, where
        prior is learned from multiple complementary data sets. It provides
        information of ChIP-seq signals and must have at least the first six
        BED columns. All files can be either ungzipped or gzipped with a
        suffix '.gz' or '.gzip'. When this option is specified, the option
        '--partition-model <string>' will be set to 'cmb_lgt' automatically.
        (Default: "")

    --cap-stacked-chipseq-reads
        Keep a maximum number of ChIP-seq reads that aligned to the same
        genomic interval. This option is used when running prior-enhanced
        RSEM, where prior is learned from multiple complementary data sets.
        This option is only in use when either
        '--chipseq-read-files-multi-targets <string>' or

# 5、获得表达量矩阵：genes.TMM.EXPR.matrix

abundance_estimates_to_matrix.pl  \
    --est_method featureCounts \
    --gene_trans_map gene_trans_map.txt \
    --quant_files genes.quant_files.txt \
    --out_prefix genes

In [274]:
with open(annotation_gtf, 'r') as f:
    lines = f.readlines()

In [ ]:
# remove featureCounts_outputs header
for file in os.listdir('outputs/featureCounts_outputs/'):
    if not file.endswith('.featurecounts.txt'):
        continue

    with open(f'outputs/featureCounts_outputs/{file}', 'r') as f:
        a =f.readlines()

    with open(f'outputs/featureCounts_outputs/{file.replace(".txt", ".noheader.txt")}', 'w') as f:
        for line in a[1:]:
            f.write(line)

In [325]:
with open('grcm38_gene_trans_map.txt', 'w') as f:
    for line in lines:
        line_info = line.split('\t')
        if len(line_info) == 1:
            continue
            
        if line_info[2] != 'transcript':
            continue
            
        gene_id = re.search('gene_id "(.*?)"', lines[i]).group(1)
        transcript_id = re.search('transcript_id "(.*?)"', lines[i]).group(1)

        f.write(f'{gene_id}\t{transcript_id}\n')

In [ ]:
def cal_fpkm(featureCounts_txt):
    
    # featureCounts
    
    featureCounts_df = pd.read_csv(featureCounts_txt, sep = '\t')

    featureCounts_df['FPKM'] = 0
    
    count_column = featureCounts_df.columns[-2]
    
    read_sum = featureCounts_df[count_column].sum()
    
    for i in featureCounts_df.index:

        read_count = featureCounts_df.loc[i, count_column]

        gene_length = featureCounts_df.loc[i, 'Length']

        fpkm = 10**9 * read_count / (read_sum * gene_length)
        
        featureCounts_df.loc[i, 'FPKM'] = fpkm

    return featureCounts_df

fpkm_matrix_df = pd.DataFrame()

for sample in ['3dpi_0', '5dpi_0',
               '3dpi_HY', '5dpi_HY', 
               '3dpi_T7', '5dpi_T7', 
               '3dpi_KT', '5dpi_KT',
               '3dpi_N289D', '5dpi_N289D']:
    
    print(sample)
    
    df = cal_fpkm(f'outputs/featureCounts_outputs/{sample}_C57mouse_Lung.featurecounts.noheader.txt')
    
    for i in df.index:
        gene_id = df.loc[i, 'Geneid']
        fpkm = df.loc[i, 'FPKM']
        
        fpkm_matrix_df.loc[gene_id, sample] = fpkm

3dpi_0
5dpi_0
3dpi_HY
5dpi_HY
3dpi_T7
5dpi_T7
3dpi_KT
5dpi_KT
3dpi_N289D
5dpi_N289D

In [ ]:
np.log2(fpkm_matrix_df+1).to_csv('outputs/featureCounts_outputs/fpkm.log2.matrix', sep = '\t')

In [4]:
fpkm_matrix_log2_df = pd.read_csv('outputs/featureCounts_outputs/fpkm.log2.matrix', sep = '\t', index_col = 0)
fpkm_matrix_log2_df

,3dpi_0,5dpi_0,3dpi_HY,5dpi_HY,3dpi_T7,5dpi_T7,3dpi_KT,5dpi_KT,3dpi_N289D,5dpi_N289D
ENSMUSG00000102693,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
ENSMUSG00000064842,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
ENSMUSG00000051951,0.010370,0.129302,0.045973,0.099475,0.013295,0.064096,0.102652,0.050408,0.020927,0.027729
ENSMUSG00000102851,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
ENSMUSG00000103377,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...
ENSMUSG00000094431,0.000000,0.000000,0.000000,0.000000,0.000000,0.323866,0.000000,0.000000,0.000000,0.000000
ENSMUSG00000094621,1.493944,0.772601,0.302128,0.227983,0.302338,1.717209,0.403773,0.000000,0.000000,0.665765
ENSMUSG00000098647,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
ENSMUSG00000096730,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
ENSMUSG00000095742,5.516498,5.661503,4.923546,5.270286,4.791861,4.168786,4.791588,5.041058,4.680410,5.066482

# 6、差异表达分析

输入文件:counts.matrix

输出文件:diff_expressed_genes.txt

run_DE_analysis.pl --matrix counts.matrix --method edgeR --dispersion 0.1run_DE_analysis.pl --matrix counts.matrix --method edgeR --dispersion 0.1

In [3]:
# run_DE_analysis.pl

DE_script = 'trinityrnaseq-v2.15.1/Analysis/DifferentialExpression/run_DE_analysis.pl'

#cmd = f'perl {DE_script} --matrix {counts_txt} --method DESeq2 --samples_file {sample_txt} --contrasts {contrasts_txt} --output {DESeq2_results}'

for vs in ['0', 'HY']:

    for day in ['3', '5']:
        
        sample_txt = f'sample_vs{vs}_{day}dpi.rename.txt'
        
        contrasts_txt = f'contrasts_vs{vs}_{day}dpi.txt'
        
        method = 'edgeR'
        
        counts_txt = 'featurecounts.txt'
        
        cmd = f'perl {DE_script} --matrix {counts_txt} --method {method} --dispersion 0.1 --samples_file {sample_txt} --contrasts {contrasts_txt} --output vs_{vs}/DEG_{method}_results_{day}dpi'
        
        print(cmd)
        
        os.system(cmd)

perl trinityrnaseq-v2.15.1/Analysis/DifferentialExpression/run_DE_analysis.pl --matrix featurecounts.txt --method edgeR --dispersion 0.1 --samples_file sample_vs0_3dpi.rename.txt --contrasts contrasts_vs0_3dpi.txt --output vs_0/DEG_edgeR_results_3dpi
$VAR1 = {
          '3dpi_HY' => [
                         '3dpi_HY'
                       ],
          '3dpi_T7' => [
                         '3dpi_T7'
                       ],
          '3dpi_N289D' => [
                            '3dpi_N289D'
                          ],
          '3dpi_0' => [
                        '3dpi_0'
                      ],
          '3dpi_KT' => [
                         '3dpi_KT'
                       ]
        };
CMD: Rscript featurecounts.txt.3dpi_HY_vs_3dpi_0.3dpi_HY.vs.3dpi_0.EdgeR.Rscript

Got 16 samples, and got: 16 data fields.
Header: Geneid	Chr	Start	End	Strand	Length	5dpi_N289D	3dpi_KT	5dpi_HY	3dpi_HY	5dpi_T7	5dpi_0	3dpi_T7	3dpi_0	3dpi_N289D	5dpi_KT
Next: ENSMUSG00000102693	1	3073253	3074322	+	1070	0	0	0	0	0	0	0	0	0	0

-shifting sample indices over.
$VAR1 = {
          'Strand' => 4,
          '5dpi_HY' => 8,
          '3dpi_KT' => 7,
          '3dpi_T7' => 12,
          '5dpi_N289D' => 6,
          '3dpi_0' => 13,
          'End' => 3,
          '5dpi_0' => 11,
          'Length' => 5,
          '3dpi_N289D' => 14,
          '5dpi_T7' => 10,
          '3dpi_HY' => 9,
          '5dpi_KT' => 15,
          'Start' => 2,
          'Chr' => 1
        };
Contrasts to perform are: $VAR1 = [
          [
            '3dpi_HY',
            '3dpi_0'
          ],
          [
            '3dpi_KT',
            '3dpi_0'
          ],
          [
            '3dpi_T7',
            '3dpi_0'
          ],
          [
            '3dpi_N289D',
            '3dpi_0'
          ]
        ];
Loading required package: edgeR
Loading required package: limma

null device
          1
CMD: Rscript featurecounts.txt.3dpi_KT_vs_3dpi_0.3dpi_KT.vs.3dpi_0.EdgeR.Rscript

Loading required package: edgeR
Loading required package: limma

null device
          1
CMD: Rscript featurecounts.txt.3dpi_T7_vs_3dpi_0.3dpi_T7.vs.3dpi_0.EdgeR.Rscript

Loading required package: edgeR
Loading required package: limma

null device
          1
CMD: Rscript featurecounts.txt.3dpi_N289D_vs_3dpi_0.3dpi_N289D.vs.3dpi_0.EdgeR.Rscript

Loading required package: edgeR
Loading required package: limma

null device
          1
perl trinityrnaseq-v2.15.1/Analysis/DifferentialExpression/run_DE_analysis.pl --matrix featurecounts.txt --method edgeR --dispersion 0.1 --samples_file sample_vs0_5dpi.rename.txt --contrasts contrasts_vs0_5dpi.txt --output vs_0/DEG_edgeR_results_5dpi
$VAR1 = {
          '5dpi_N289D' => [
                            '5dpi_N289D'
                          ],
          '5dpi_0' => [
                        '5dpi_0'
                      ],
          '5dpi_KT' => [
                         '5dpi_KT'
                       ],
          '5dpi_HY' => [
                         '5dpi_HY'
                       ],
          '5dpi_T7' => [
                         '5dpi_T7'
                       ]
        };
CMD: Rscript featurecounts.txt.5dpi_HY_vs_5dpi_0.5dpi_HY.vs.5dpi_0.EdgeR.Rscript

Got 16 samples, and got: 16 data fields.
Header: Geneid	Chr	Start	End	Strand	Length	5dpi_N289D	3dpi_KT	5dpi_HY	3dpi_HY	5dpi_T7	5dpi_0	3dpi_T7	3dpi_0	3dpi_N289D	5dpi_KT
Next: ENSMUSG00000102693	1	3073253	3074322	+	1070	0	0	0	0	0	0	0	0	0	0

-shifting sample indices over.
$VAR1 = {
          'End' => 3,
          '5dpi_KT' => 15,
          '3dpi_HY' => 9,
          '3dpi_N289D' => 14,
          'Start' => 2,
          'Chr' => 1,
          '5dpi_HY' => 8,
          '3dpi_KT' => 7,
          '5dpi_N289D' => 6,
          'Strand' => 4,
          'Length' => 5,
          '3dpi_T7' => 12,
          '5dpi_0' => 11,
          '5dpi_T7' => 10,
          '3dpi_0' => 13
        };
Contrasts to perform are: $VAR1 = [
          [
            '5dpi_HY',
            '5dpi_0'
          ],
          [
            '5dpi_KT',
            '5dpi_0'
          ],
          [
            '5dpi_T7',
            '5dpi_0'
          ],
          [
            '5dpi_N289D',
            '5dpi_0'
          ]
        ];
Loading required package: edgeR
Loading required package: limma

null device
          1
CMD: Rscript featurecounts.txt.5dpi_KT_vs_5dpi_0.5dpi_KT.vs.5dpi_0.EdgeR.Rscript

Loading required package: edgeR
Loading required package: limma

null device
          1
CMD: Rscript featurecounts.txt.5dpi_T7_vs_5dpi_0.5dpi_T7.vs.5dpi_0.EdgeR.Rscript

Loading required package: edgeR
Loading required package: limma

null device
          1
CMD: Rscript featurecounts.txt.5dpi_N289D_vs_5dpi_0.5dpi_N289D.vs.5dpi_0.EdgeR.Rscript

Loading required package: edgeR
Loading required package: limma

null device
          1
perl trinityrnaseq-v2.15.1/Analysis/DifferentialExpression/run_DE_analysis.pl --matrix featurecounts.txt --method edgeR --dispersion 0.1 --samples_file sample_vsHY_3dpi.rename.txt --contrasts contrasts_vsHY_3dpi.txt --output vs_HY/DEG_edgeR_results_3dpi
$VAR1 = {
          '3dpi_KT' => [
                         '3dpi_KT'
                       ],
          '3dpi_T7' => [
                         '3dpi_T7'
                       ],
          '3dpi_HY' => [
                         '3dpi_HY'
                       ],
          '3dpi_N289D' => [
                            '3dpi_N289D'
                          ]
        };
CMD: Rscript featurecounts.txt.3dpi_KT_vs_3dpi_HY.3dpi_KT.vs.3dpi_HY.EdgeR.Rscript

Got 16 samples, and got: 16 data fields.
Header: Geneid	Chr	Start	End	Strand	Length	5dpi_N289D	3dpi_KT	5dpi_HY	3dpi_HY	5dpi_T7	5dpi_0	3dpi_T7	3dpi_0	3dpi_N289D	5dpi_KT
Next: ENSMUSG00000102693	1	3073253	3074322	+	1070	0	0	0	0	0	0	0	0	0	0

-shifting sample indices over.
$VAR1 = {
          '3dpi_KT' => 7,
          'Start' => 2,
          'End' => 3,
          'Chr' => 1,
          '5dpi_KT' => 15,
          '5dpi_0' => 11,
          '3dpi_0' => 13,
          'Length' => 5,
          '5dpi_T7' => 10,
          '5dpi_N289D' => 6,
          '5dpi_HY' => 8,
          'Strand' => 4,
          '3dpi_T7' => 12,
          '3dpi_N289D' => 14,
          '3dpi_HY' => 9
        };
Contrasts to perform are: $VAR1 = [
          [
            '3dpi_KT',
            '3dpi_HY'
          ],
          [
            '3dpi_T7',
            '3dpi_HY'
          ],
          [
            '3dpi_N289D',
            '3dpi_HY'
          ]
        ];
Loading required package: edgeR
Loading required package: limma

null device
          1
CMD: Rscript featurecounts.txt.3dpi_T7_vs_3dpi_HY.3dpi_T7.vs.3dpi_HY.EdgeR.Rscript

Loading required package: edgeR
Loading required package: limma

null device
          1
CMD: Rscript featurecounts.txt.3dpi_N289D_vs_3dpi_HY.3dpi_N289D.vs.3dpi_HY.EdgeR.Rscript

Loading required package: edgeR
Loading required package: limma

null device
          1
perl trinityrnaseq-v2.15.1/Analysis/DifferentialExpression/run_DE_analysis.pl --matrix featurecounts.txt --method edgeR --dispersion 0.1 --samples_file sample_vsHY_5dpi.rename.txt --contrasts contrasts_vsHY_5dpi.txt --output vs_HY/DEG_edgeR_results_5dpi
$VAR1 = {
          '5dpi_T7' => [
                         '5dpi_T7'
                       ],
          '5dpi_KT' => [
                         '5dpi_KT'
                       ],
          '5dpi_N289D' => [
                            '5dpi_N289D'
                          ],
          '5dpi_HY' => [
                         '5dpi_HY'
                       ]
        };
CMD: Rscript featurecounts.txt.5dpi_KT_vs_5dpi_HY.5dpi_KT.vs.5dpi_HY.EdgeR.Rscript

Got 16 samples, and got: 16 data fields.
Header: Geneid	Chr	Start	End	Strand	Length	5dpi_N289D	3dpi_KT	5dpi_HY	3dpi_HY	5dpi_T7	5dpi_0	3dpi_T7	3dpi_0	3dpi_N289D	5dpi_KT
Next: ENSMUSG00000102693	1	3073253	3074322	+	1070	0	0	0	0	0	0	0	0	0	0

-shifting sample indices over.
$VAR1 = {
          'Chr' => 1,
          '5dpi_N289D' => 6,
          '5dpi_T7' => 10,
          '3dpi_HY' => 9,
          '5dpi_0' => 11,
          'Length' => 5,
          '5dpi_KT' => 15,
          'Strand' => 4,
          '3dpi_0' => 13,
          'Start' => 2,
          '3dpi_T7' => 12,
          '5dpi_HY' => 8,
          'End' => 3,
          '3dpi_N289D' => 14,
          '3dpi_KT' => 7
        };
Contrasts to perform are: $VAR1 = [
          [
            '5dpi_KT',
            '5dpi_HY'
          ],
          [
            '5dpi_T7',
            '5dpi_HY'
          ],
          [
            '5dpi_N289D',
            '5dpi_HY'
          ]
        ];
Loading required package: edgeR
Loading required package: limma

null device
          1
CMD: Rscript featurecounts.txt.5dpi_T7_vs_5dpi_HY.5dpi_T7.vs.5dpi_HY.EdgeR.Rscript

Loading required package: edgeR
Loading required package: limma

null device
          1
CMD: Rscript featurecounts.txt.5dpi_N289D_vs_5dpi_HY.5dpi_N289D.vs.5dpi_HY.EdgeR.Rscript

Loading required package: edgeR
Loading required package: limma

null device
          1

In [18]:
pd.read_csv('FPKM.csv', index_col=0)

,3dpi_0,3dpi_HY,3dpi_N289D,3dpi_K412R/T480A,3dpi_ΔL226/R229I,5dpi_0,5dpi_HY,5dpi_N289D,5dpi_K412R/T480A,5dpi_ΔL226/R229I
ENSMUSG00000051951,0.165957,1.353919,0.004391,0.107838,0.012906,0.060900,0.046425,0.053060,0.186240,0.228792
ENSMUSG00000102331,0.004346,0.264897,0.000000,0.000000,0.000000,0.033157,0.000000,0.000000,0.000000,0.000000
ENSMUSG00000102343,0.006453,0.000000,0.000000,0.000000,0.000000,0.098722,0.000000,0.000000,0.004185,0.000000
ENSMUSG00000025900,1.451405,30.608244,1.003202,0.699032,14.612404,6.153525,4.823649,9.131228,2.178156,1.762423
ENSMUSG00000025902,5.711609,167.324596,164.156387,8.259482,35.051636,36.521312,3.456206,5.071236,11.399467,10.857966
...,...,...,...,...,...,...,...,...,...,...
ENSMUSG00000063897,12.871712,2.347247,1.558404,0.432667,1.374958,4.720083,60.473749,5.866276,8.584109,2.019462
ENSMUSG00000084520,0.000000,0.006356,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.002311,0.000000
ENSMUSG00000094431,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.014568
ENSMUSG00000094621,0.016721,0.026149,0.000000,0.067702,0.005893,0.044209,0.089366,0.250476,0.000000,0.071662
ENSMUSG00000095742,2.001351,5.078870,1.289415,4.426724,0.650957,4.632851,51.337497,3.958805,3.422455,0.387725

In [19]:
np.log2(pd.read_csv('FPKM.csv', index_col=0)+1).to_csv('FPKM_log2.matrix')

In [ ]:
# analyze_diff_expr.pl

# run in DEG_edgeR_results

for vs in ['0', 'HY']:

    for day in ['3', '5']:

        DE_script = '/Users/chenrujian/Desktop/转录组/trinityrnaseq-v2.15.1/Analysis/DifferentialExpression/analyze_diff_expr.pl'

        matrix = '/Users/chenrujian/Desktop/转录组/fpkm.log2.matrix'

        sample_txt = f'/Users/chenrujian/Desktop/转录组/sample_vs{vs}_{day}dpi.rename.txt'

        cmd = f'{DE_script} --matrix {matrix} --samples {sample_txt} -P 0.05 -C 1'

        print(f'{cmd}\n')

/Users/chenrujian/Desktop/转录组/trinityrnaseq-v2.15.1/Analysis/DifferentialExpression/analyze_diff_expr.pl --matrix /Users/chenrujian/Desktop/转录组/fpkm.log2.matrix --samples /Users/chenrujian/Desktop/转录组/sample_vs0_3dpi.rename.txt -P 0.05 -C 1

/Users/chenrujian/Desktop/转录组/trinityrnaseq-v2.15.1/Analysis/DifferentialExpression/analyze_diff_expr.pl --matrix /Users/chenrujian/Desktop/转录组/fpkm.log2.matrix --samples /Users/chenrujian/Desktop/转录组/sample_vs0_5dpi.rename.txt -P 0.05 -C 1

/Users/chenrujian/Desktop/转录组/trinityrnaseq-v2.15.1/Analysis/DifferentialExpression/analyze_diff_expr.pl --matrix /Users/chenrujian/Desktop/转录组/fpkm.log2.matrix --samples /Users/chenrujian/Desktop/转录组/sample_vsHY_3dpi.rename.txt -P 0.05 -C 1

/Users/chenrujian/Desktop/转录组/trinityrnaseq-v2.15.1/Analysis/DifferentialExpression/analyze_diff_expr.pl --matrix /Users/chenrujian/Desktop/转录组/fpkm.log2.matrix --samples /Users/chenrujian/Desktop/转录组/sample_vsHY_5dpi.rename.txt -P 0.05 -C 1

In [ ]:
/Users/chenrujian/Desktop/转录组/trinityrnaseq-v2.15.1/Analysis/DifferentialExpression/analyze_diff_expr.pl --matrix /Users/chenrujian/Desktop/转录组/featurecounts.txt --samples /Users/chenrujian/Desktop/转录组/sample_vs0_3dpi.rename.txt -P 0.05 -C 1

# 将基因划分为表达簇

  $TRINITY_HOME/Analysis/DifferentialExpression/define_clusters_by_cutting_tree.pl \
                                    -R  diffExpr.P0.001_C2.matrix.RData --Ptree 60

In [884]:
# 在DEG_edgeR_results/（或拆分后的DEG_edgeR_results_split/sample/）目录下执行

cluster_script = '/home/chenrujian/trinityrnaseq-v2.15.1/Analysis/DifferentialExpression/define_clusters_by_cutting_tree.pl'

cmd = f'{cluster_script} -R diffExpr.P0.05_C2.matrix.RData --Ptree 60'

print(cmd)

/home/chenrujian/trinityrnaseq-v2.15.1/Analysis/DifferentialExpression/define_clusters_by_cutting_tree.pl -R diffExpr.P0.05_C2.matrix.RData --Ptree 60

In [ ]:
cluster_path = 'outputs/DEG_edgeR_results/diffExpr.P0.001_C2.matrix.RData.clusters_fixed_P_60'

os.system(f'chmod 777 {cluster_path}/__tmp_plot_clusters.R')

for i in os.listdir(cluster_path):
    if not i.endswith('.matrix'):
        continue
    matrix_df = pd.read_csv(os.path.join(cluster_path, i), sep = '\t')
    matrix_df = matrix_df[['3dpi_0', '5dpi_0', 
               '3dpi_HY', '5dpi_HY', 
               '3dpi_KT', '5dpi_KT', 
               '3dpi_T7', '5dpi_T7', 
               '3dpi_N289D', '5dpi_N289D', ]]
    matrix_df.to_csv(os.path.join(cluster_path, i), sep = '\t')

print('Rscript __tmp_plot_clusters.R')

Rscript __tmp_plot_clusters.R

# 功能富集

In [504]:
import pyclusterprofiler
from Ensembl_converter import EnsemblConverter

# Create an instance of EnsemblConverter
converter = EnsemblConverter()

In [ ]:
# cluster
cluster_path = 'outputs/DEG_edgeR_results/diffExpr.P0.001_C2.matrix.RData.clusters_fixed_P_60'
cluster_df = pd.DataFrame()
for file in os.listdir(cluster_path):
    if not file.endswith('.matrix'):
        continue
    sub_df = pd.read_csv(os.path.join(cluster_path, file), sep = '\t', index_col = 0)
    sub_df['cluster'] = file.split('_')[1]
    cluster_df = pd.concat([cluster_df, sub_df], axis = 0)
cluster_df

,3dpi_0,5dpi_0,3dpi_HY,5dpi_HY,3dpi_KT,5dpi_KT,3dpi_T7,5dpi_T7,3dpi_N289D,5dpi_N289D,cluster
ENSMUSG00000066108,0.438599,0.369218,0.497305,-0.926419,0.512990,-0.111107,-0.293476,-1.113640,-0.035127,0.661657,6
ENSMUSG00000029273,1.007265,0.753711,-0.026233,-0.509139,0.467544,-0.102494,-0.960756,-0.334545,-0.557997,0.262642,6
ENSMUSG00000020581,0.241598,-0.070169,0.508851,-0.613420,0.411096,0.167218,-0.473578,-0.471598,-0.401148,0.701151,6
ENSMUSG00000030017,0.477450,0.336721,0.626127,-0.730594,0.597377,-0.120561,-0.597278,-0.720608,-0.577350,0.708715,6
ENSMUSG00000064057,0.762159,0.603964,0.282125,-0.512069,0.277633,0.000931,-0.196490,-1.196406,-0.407299,0.385452,6
...,...,...,...,...,...,...,...,...,...,...,...
ENSMUSG00000030546,1.096168,0.460191,-0.373617,0.646032,0.367679,-0.844594,0.060664,-0.415580,-0.843111,-0.153832,4
ENSMUSG00000027513,1.213209,0.174066,-0.895257,0.699447,0.736912,-1.092472,-0.144049,0.231369,-0.685841,-0.237384,4
ENSMUSG00000095633,-0.647395,0.027543,1.722594,-0.616296,0.328250,0.540762,-0.682634,0.185636,-0.532743,-0.325718,7
ENSMUSG00000076569,0.652913,-0.559763,-0.328888,0.995197,-0.328239,0.443036,-0.871674,0.018343,-0.280933,0.260008,3
ENSMUSG00000004814,-0.240763,-0.776930,-0.687636,0.441780,-0.393489,1.025210,-0.889258,0.632356,0.191427,0.697303,3

In [ ]:
symbol_df = converter.convert_ids(cluster_df.index.tolist())
symbol_df

                   ENSG    Symbol
0    ENSMUSG00000066108     Muc5b
1    ENSMUSG00000029273   Sult1d1
2    ENSMUSG00000020581      Agr2
3    ENSMUSG00000030017     Reg3g
4    ENSMUSG00000064057   Scgb3a1
..                  ...       ...
682  ENSMUSG00000030546     Plin1
683  ENSMUSG00000027513      Pck1
684  ENSMUSG00000095633  Igkv4-58
685  ENSMUSG00000076569  Igkv5-39
686  ENSMUSG00000004814     Ccl24

[687 rows x 2 columns]

In [ ]:
id2genename = {}
gene_info_df = pd.read_csv('id2genename.txt', sep = '\t')
gene_info_df['symbol'] = ''
for i in gene_info_df.index:
    gene_name = gene_info_df.loc[i, 'Gene Name']
    symbol = gene_name.split('(')[1].split(')')[0]
    gene_info_df.loc[i, 'symbol'] = symbol
    id2genename[gene_info_df.loc[i, 'From']] = symbol
gene_info_df

In [ ]:
unname_geneid_list = []
for geneid in fpkm_matrix_log2_df.index.tolist():
    if geneid not in gene_info_df['From'].tolist():
        unname_geneid_list.append(geneid)
new_symbol_df = converter.convert_ids(unname_geneid_list)
new_symbol_df

In [ ]:
# symbol
for i in cluster_df.index:
    symbol = symbol_df.loc[symbol_df['ENSG']==i, 'Symbol'].item()
    if symbol == '-':
        cluster_df.loc[i, 'symbol'] = '-'
    else:
        cluster_df.loc[i, 'symbol'] = symbol
cluster_df

In [ ]:
sample_A = '5dpi_T7'
sample_B = '5dpi_HY'

count_result = pd.read_csv(f'outputs/DEG_edgeR_results/featurecounts.rename.noheader.matrix.{sample_A}_vs_{sample_B}.edgeR.count_matrix', sep = '\t')
de_result = pd.read_csv(f'outputs/DEG_edgeR_results/featurecounts.rename.noheader.matrix.{sample_A}_vs_{sample_B}.edgeR.DE_results', sep = '\t')

de_result = de_result[abs(de_result['logFC']) > 0]

de_result = de_result[de_result['PValue'] <= 0.05]

'''
for i in de_result.index:
    symbol = symbol_df.loc[symbol_df['ENSG']==i, 'Symbol'].item()
    if symbol == '-':
        de_result.loc[i, 'symbol'] = '-'
    else:
        de_result.loc[i, 'symbol'] = symbol'''

for i in de_result.index:
    sampleA_count = count_result.loc[i, f'X{sample_A}']
    sampleB_count = count_result.loc[i, f'X{sample_B}']
    de_result.loc[i, 'sampleA'] = sampleA_count
    de_result.loc[i, 'sampleB'] = sampleB_count
    
de_result = de_result.rename(columns = {'sampleA':sample_A, 'sampleB':sample_B})

de_result = de_result.sort_values(by = 'logFC', ascending = False)
de_result

In [12]:
featureCounts_txt = 'outputs/featureCounts_outputs/3dpi_0_C57mouse_Lung.featurecounts.noheader.txt'
featureCounts_df = pd.read_csv(featureCounts_txt, sep = '\t')
featureCounts_df

,Geneid,Chr,Start,End,Strand,Length,outputs/hisat2_outputs/3dpi_0_C57mouse_Lung.sorted.bam
0,ENSMUSG00000102693,1,3073253,3074322,+,1070,0
1,ENSMUSG00000064842,1,3102016,3102125,+,110,0
2,ENSMUSG00000051951,1;1;1;1;1;1;1,3205901;3206523;3213439;3213609;3214482;342170...,3207317;3207317;3215632;3216344;3216968;342190...,-;-;-;-;-;-;-,6094,2
3,ENSMUSG00000102851,1,3252757,3253236,+,480,0
4,ENSMUSG00000103377,1,3365731,3368549,-,2819,0
...,...,...,...,...,...,...,...
47724,ENSMUSG00000094431,GL456385.1,32719,32818,+,100,0
47725,ENSMUSG00000094621,GL456372.1,13262,13382,-,121,10
47726,ENSMUSG00000098647,GL456381.1,16623,16721,-,99,0
47727,ENSMUSG00000096730,JH584292.1;JH584292.1;JH584292.1;JH584292.1;JH...,3536;3536;3536;3539;3573;5658;5658;5658;5658;6...,3826;3826;3826;3826;3826;5940;5940;5940;5940;7...,+;+;+;+;+;+;+;+;+;+;+;+;+;+;+;+;+;+;+;+;+;+;+;+;+,3077,0
47728,ENSMUSG00000095742,JH584295.1;JH584295.1;JH584295.1;JH584295.1;JH...,66;565;708;972;986;1014;1440,109;633;752;981;1009;1024;1479,-;-;-;-;-;-;-,243,495

In [7]:
for vs in ['HY']:
    for day_post_infection in [3, 5]:
        for sample in ['N289D', 'KT', 'T7']:
            de_result_path = f'vs_{vs}_bak/DEG_edgeR_results_{day_post_infection}dpi/featurecounts.rename.noheader.{day_post_infection}dpi.matrix.{day_post_infection}dpi_{sample}_vs_{day_post_infection}dpi_HY.edgeR.DE_results'
            sample_name = f'{day_post_infection}dpi_{sample}'
            print(sample_name, os.path.exists(de_result_path))

3dpi_N289D True
3dpi_KT True
3dpi_T7 True
5dpi_N289D True
5dpi_KT True
5dpi_T7 True